openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0
tags:
  - name: ai
    description: AI-powered endpoints
components:
  schemas:
    EnhanceRequest:
      type: object
      properties:
        original:
          type: string
          description: The original project description
          maxLength: 250
      required:
        - original
    EnhanceSuccess:
      type: object
      properties:
        original:
          type: string
          description: The original description that was submitted
        enhanced:
          type: string
          description: The AI-enhanced description
      required:
        - original
        - enhanced
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          enum:
            - INVALID_DESCRIPTION
            - TOO_MANY_REQUESTS
            - GATEWAY_ERROR
        message:
          type: string
      required:
        - error
        - message

paths:
  /ai/project-description/enhance:
    post:
      tags: ["ai"]
      summary: Enhance a project description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnhanceRequest"
      responses:
        "200":
          description: Successfully enhanced the project description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnhanceSuccess"
        "400":
          description: Invalid input - we were not able to generate an enhanced description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: There was an error with the upstream AI gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
