openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0
tags:
  - name: ai
    description: AI-powered endpoints
components:
  schemas:
    EnhanceRequest:
      type: object
      properties:
        original:
          type: string
          description: The original project description
          maxLength: 250
        flowId:
          type: string
          format: uuid
          description: Flow ID for logging and audit purposes
        modelId:
          type: string
          description: Optional ID of the AI model to prompt via AI Gateway
          # this list should be kept in sync with ACCEPTED_MODEL_IDS in ./constants.ts
          enum:
            - google/gemini-2.5-pro
            - google/gemini-2.5-flash
            - google/gemini-3-pro-preview
            - google/gemini-3-flash
        sessionId:
          type: string
          format: uuid
          description: Optional session ID for logging and audit purposes
      required:
        - original
        - flowId
    EnhanceSuccess:
      type: object
      properties:
        original:
          type: string
          description: The original description that was submitted
        enhanced:
          type: string
          description: The AI-enhanced description
      required:
        - original
        - enhanced
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          # see ./types.ts for source of these values
          enum:
            - INVALID_INPUT
            - TOO_MANY_REQUESTS
            - GUARDRAIL_TRIPPED
        message:
          type: string
      required:
        - error
        - message

paths:
  /ai/project-description/enhance:
    post:
      tags: ["ai"]
      summary: Enhance a project description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnhanceRequest"
      responses:
        "200":
          description: Successfully enhanced the project description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnhanceSuccess"
        "400":
          description: Invalid input - we were not able to generate an enhanced description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          $ref: "#/components/responses/ErrorMessage"
