import type { GetObjectCommandOutput, S3 } from "@aws-sdk/client-s3";
import { isBefore, isValid, parseISO } from "date-fns";

/**
 * Tags written by the Scanii callback Lambda once it has scanned an object.
 * `ScaniiFindings` is always written alongside `ScaniiId`.
 */
export const SCANII_ID_TAG = "ScaniiId";
export const SCANII_FINDINGS_TAG = "ScaniiFindings";

/**
 * A lack of `ScaniiFindings` mean "scanned, nothing found".
 *
 * In practice the Lambda writes the literal string `None` for a clean file.
 * Empty is kept as a defensive second case.
 */
const CLEAN_FINDINGS_VALUES = new Set(["", "none"]);

/**
 * Object metadata marking a file as generated by the API itself, rather than uploaded by a
 * user. Set at PutObject time, so it is never derived from user input.
 */
export const SCAN_EXEMPT_METADATA_KEY = "scan_exempt";

export type ScanStatus =
  | { status: "clean" }
  | { status: "pending" }
  // we don't expect to see this final status - Scanii is set up to delete anything it reads as malicious
  | { status: "malicious"; findings: string };

const CLEAN: ScanStatus = { status: "clean" };
const PENDING: ScanStatus = { status: "pending" };

/** The subset of a GetObject response we need to reach a verdict */
type ScannableObject = Pick<
  GetObjectCommandOutput,
  "Metadata" | "TagCount" | "LastModified"
>;

/**
 * Establish whether Scanii has scanned an object in the user-data bucket.
 *
 * Everything landing in that bucket is scanned by a pair of Lambdas (managed elsewhere),
 * and anything Scanii flags is deleted immediately. The callback tags each object it
 * has seen, so the presence of `ScaniiId` is our proof that a scan happened.
 *
 * Checks are ordered so that every short-circuit costs zero extra S3 calls - only
 * an object that is genuinely tagged pays for a GetObjectTagging round trip.
 */
export const getScanStatus = async (
  s3: S3,
  key: string,
  file: ScannableObject,
): Promise<ScanStatus> => {
  // API-generated files (e.g. the ODP payload JSON) contain no user inputs and are handed to
  // councils immediately after upload - too soon for a scan to have landed - so we exempt them
  if (file.Metadata?.[SCAN_EXEMPT_METADATA_KEY] === "true") return CLEAN;

  const enforceFrom = getEnforcementDate();

  // Unset enforcement date means the guard is off. That is the state in local development
  // and in e2e/integration tests, which run against Minio - there is no Scanii equivalent
  // behind it, so nothing is ever scanned or tagged. Every environment backed by a real
  // bucket (pizzas, staging, and production) has a scanner attached and enforces!
  if (!enforceFrom) return CLEAN;

  // We don't expect objects predating Scanii upgrade to be tagged
  // i.e. we assume that anything before cutoff was scanned
  if (file.LastModified && isBefore(file.LastModified, enforceFrom))
    return CLEAN;

  // S3 returns the tag count on GetObject (no tags => not yet scanned)
  if (!file.TagCount) return PENDING;

  // at this point we have to make a further request to get the actual tags
  const { TagSet } = await s3.getObjectTagging({
    Bucket: process.env.AWS_S3_BUCKET,
    Key: key,
  });
  const tags = Object.fromEntries(
    (TagSet ?? []).map(({ Key, Value }) => [Key, Value]),
  );

  // tagged, but not by Scanii (unexpected, but we guard against it)
  if (!tags[SCANII_ID_TAG]) return PENDING;

  const findings = tags[SCANII_FINDINGS_TAG]?.trim() ?? "";
  return isCleanFindings(findings) ? CLEAN : { status: "malicious", findings };
};

// whether a `ScaniiFindings` tag value represents a file that was scanned and found clean
const isCleanFindings = (findings: string): boolean =>
  CLEAN_FINDINGS_VALUES.has(findings.toLowerCase());

/**
 * Read the enforcement cutoff, or undefined if the guard is disabled.
 * A malformed value throws rather than silently disabling the guard.
 */
const getEnforcementDate = (): Date | undefined => {
  const raw = process.env.ENFORCE_SCAN_FROM;
  if (!raw) return undefined;

  const parsed = parseISO(raw);
  if (!isValid(parsed)) {
    throw new Error(
      `Invalid ENFORCE_SCAN_FROM: expected an ISO8601 date, got "${raw}"`,
    );
  }

  return parsed;
};
