CREATE TABLE "public"."project_types" (
  "description" text NOT NULL, 
  "value" text NOT NULL, 
  "id" serial NOT NULL, 
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "public"."project_types" IS E'A list of things people want to do within the planning system';
INSERT INTO "public"."project_types" (description, value) VALUES
  ('demolition of a building', 'demolish.full'),
  ('demolition of part of a building', 'demolish.part'),
  ('demolition of an outbuilding', 'demolish.outbuilding'),
  ('demolition of an extension', 'demolish.extension'),
  ('demolition of a boundary', 'demolish.boundary'),
  ('alteration of internal layout', 'internal'),
  ('internal alterations', 'alter.internal'),
  ('alteration of internal walls', 'alter.internal.walls'),
  ('alteration to internal floors', 'alter.internal.floors'),
  ('alteration of internal staircases', 'alter.internal.staircases'),
  ('alteration of internal doorways', 'alter.internal.doorways'),
  ('alteration of internal window openings', 'alter.internal.windows'),
  ('alteration of internal finishes', 'alter.internal.finishes'),
  ('alteration of internal services', 'alter.internal.services'),
  ('installation / replacement of kitchen units', 'alter.internal.kitchen'),
  ('installation / replacement of bathroom appliances', 'alter.internal.bathroom'),
  ('replacement of internal doors ', 'alter.internal.doors'),
  ('alterations to internal decorative features', 'alter.internal.features'),
  ('conversion of a roof space into habitable room/s', 'alter.internal.loft'),
  ('alteration of internal basements', 'alter.internal.basement'),
  ('addition of a mezzanine floor', 'alter.internal.mezzanine'),
  ('removal of part of a building', 'alter.remove'),
  ('removal of equipment', 'alter.remove.equipment'),
  ('removal of a chimney', 'alter.remove.chimney'),
  ('removal of a soil pipe', 'alter.remove.soilPipe'),
  ('removal of a hard surface', 'alter.remove.surface'),
  ('removal of a deck', 'alter.remove.deck'),
  ('removal of part of a facade', 'alter.remove.facade'),
  ('repairs to windows ', 'alter.repair.windows'),
  ('repairs to doors ', 'alter.repair.doors'),
  ('replacement of windows with windows', 'alter.replace.windowsToWindows'),
  ('replacement of doors with doors', 'alter.replace.doorsToDoors'),
  ('replacement of windows with doors', 'alter.replace.windowsToDoors'),
  ('replacement of doors with windows', 'alter.replace.doorsToWindows'),
  ('changes to door or window openings', 'alter.openings'),
  ('addition of window or door openings', 'alter.openings.add'),
  ('alteration of window or door openings', 'alter.openings.alter'),
  ('alteration of window or door openings to the rear', 'alter.openings.alter.rear'),
  ('addition of doorways to the front of the building', 'alter.openings.add.doors.front'),
  ('addition of doorways to the side of the building', 'alter.openings.add.doors.side'),
  ('addition of doorways to the rear of the building', 'alter.openings.add.doors.rear'),
  ('addition of window openings', 'alter.openings.add.windows'),
  ('addition of window openings to the front of the building', 'alter.openings.add.windows.front'),
  ('addition of window openings to the side of the building', 'alter.openings.add.windows.side'),
  ('addition of window openings to the rear of the building', 'alter.openings.add.windows.rear'),
  ('addition of high up window', 'alter.openings.add.windows.high'),
  ('addition of doors openings to the front of the building', 'alter.openings.alter.doors.front'),
  ('addition of doors openings to the side of the building', 'alter.openings.alter.doors.side'),
  ('addition of doors openings to the rear of the building', 'alter.openings.alter.doors.rear'),
  ('addition of window openings', 'alter.openings.alter.windows'),
  ('addition of window openings to the front of the building', 'alter.openings.alter.windows.front'),
  ('addition of window openings to the side of the building', 'alter.openings.alter.windows.side'),
  ('addition of window openings to the rear of the building', 'alter.openings.alter.windows.rear'),
  ('blocking-up of doorways or windows', 'alter.openings.remove'),
  ('addition of secondary glazing', 'alter.secondaryGlazing'),
  ('addition of one or more skylights', 'alter.rooflight'),
  ('alterations to facades', 'alter.facades'),
  ('alterations to facades to th rear of the building', 'alter.facades.rear'),
  ('painting of facades', 'alter.facades.paint'),
  ('cladding of facades', 'alter.facades.reclad'),
  ('addition of advert or sign', 'alter.sign'),
  ('works to drains', 'alter.drains'),
  ('alterations to tree or hedges', 'alter.trees'),
  ('alterations to hard surfaces', 'alter.surfaces'),
  ('alterations to hard surfaces', 'alter.surfaces.parking'),
  ('addition or alteration of a deck', 'alter.decks'),
  ('alterations to a boundary', 'alter.boundary'),
  ('repairs to a boundary', 'alter.boundary.repair'),
  ('repairs to a fence', 'alter.boundary.repair.fence'),
  ('repairs to a gate', 'alter.boundary.repair.gate'),
  ('repairs to a wall', 'alter.boundary.repair.wall'),
  ('replacement of a boundary', 'alter.boundary.replace'),
  ('replacement of a fence', 'alter.boundary.replace.fence'),
  ('replacement of a gate', 'alter.boundary.replace.gate'),
  ('replacement of a walll', 'alter.boundary.replace.wall'),
  ('addition of a new boundary', 'alter.boundary.add'),
  ('erection of a new fence', 'alter.boundary.add.fence'),
  ('addition of a new gate', 'alter.boundary.add.gate'),
  ('construction of a new wall', 'alter.boundary.add.wall'),
  ('addition of a chimney', 'alter.chimneys'),
  ('removal of a chimney', 'alter.remove.chimney'),
  ('alterations to the roof', 'alter.roof'),
  ('alteration of roof materials', 'alter.roof.materials'),
  ('alteration of roof shape', 'alter.roof.shape'),
  ('addition of a roof terrace', 'alter.roof.terrace'),
  ('alterations to roof parapet', 'alter.roof.parapet'),
  ('alterations to a public highway', 'alter.highways'),
  ('creation of a point of access to a highway', 'alter.highways.access'),
  ('creation of a point of access to an unclassified road', 'alter.highways.access.unclassified'),
  ('addition of a dropped kerb', 'alter.highways.droppedKerb.add'),
  ('removal of a dropped kerb', 'alter.highways.droppedKerb.remove'),
  ('addition or alteration of soil pipes', 'alter.soilPipes'),
  ('works to an external staircase', 'alter.staircase'),
  ('addition or removal of a bay window', 'alter.bayWindow'),
  ('addition of a bay window', 'alter.bayWindow.add'),
  ('removal of a bay window', 'alter.bayWindow.remove'),
  ('addition of a bay window to the rear', 'alter.bayWindow.rear'),
  ('addition of an indoor swimming pool', 'alter.swimmingPool.indoor'),
  ('addition of an outdoor swimming pool', 'alter.swimmingPool.outdoor'),
  ('addition or removal of a pond', 'alter.landscape.ponds'),
  ('addition or removal of a residential lawn or garden', 'alter.landscape.gardens'),
  ('installation of equipment', 'alter.equipment'),
  ('installation of a barbecue', 'alter.equipment.bbq'),
  ('installation of cctv', 'alter.equipment.cctv'),
  ('installation of external lighting ', 'alter.equipment.lighting'),
  ('installation of wind turbine ', 'alter.equipment.wind'),
  ('installation of antennae', 'alter.equipment.antennae'),
  ('installation of an aerial', 'alter.equipment.antennae.aerial'),
  ('installation of a satellite dish', 'alter.equipment.antennae.dish'),
  ('installation of solar panel', 'alter.equipment.solar'),
  ('installation of security alarm ', 'alter.equipment.alarm'),
  ('installation of tank ', 'alter.equipment.tank'),
  ('installation of heat pump (air)', 'alter.equipment.heatPump.air'),
  ('installation of heat pump (ground)', 'alter.equipment.heatPump.ground'),
  ('installation of heat pump (water)', 'alter.equipment.heatPump.water'),
  ('installation of biomass / CHP', 'alter.equipment.biomass'),
  ('installation of an electric vehicle charging point', 'alter.equipment.charging'),
  ('installation of industrial equipment', 'alter.equipment.industrial'),
  ('installation of cables ', 'alter.cables'),
  ('installation of pipes', 'alter.pipes'),
  ('extension to the rear or side', 'extend.rearSide'),
  ('extension to the rear', 'extend.rearSide.rear'),
  ('extension to the side', 'extend.rearSide.side'),
  ('extension to the front', 'extend.front'),
  ('upper storey extension', 'extend.upperStorey'),
  ('roof extension', 'extend.roof'),
  ('addition of a roof dormer', 'extend.roof.dormer'),
  ('addition of a mansard roof', 'extend.roof.mansard'),
  ('hip-to-gable roof enlargement', 'extend.roof.hiptogable'),
  ('addition of one or more new storeys', 'extend.roof.newstorey'),
  ('connection of parts of a roof', 'extend.roof.connect'),
  ('alteration of roof shape', 'extend.roof.shape'),
  ('addition of a new storey', 'extend.roof.newstorey'),
  ('basement extension ', 'extend.basement'),
  ('enlargement of a basement', 'extend.basement.extend'),
  ('addition of a lightwell', 'extend.basement.lightwell'),
  ('addition of an outbuilding', 'extend.outbuilding.garage'),
  ('addition of garage', 'extend.outbuilding.garage'),
  ('addition of shed', 'extend.outbuilding.shed'),
  ('addition of garden office', 'extend.outbuilding.office'),
  ('addition of a roof shelter', 'extend.outbuilding.shelter'),
  ('additon of sauna', 'extend.outbuilding.sauna'),
  ('addition of store', 'extend.outbuilding.store'),
  ('addition of gym', 'extend.outbuilding.gym'),
  ('addition of summer house', 'extend.outbuilding.summerHouse'),
  ('addition of greenhouse', 'extend.outbuilding.greenhouse'),
  ('addition of other outbuilding', 'extend.outbuilding.other'),
  ('addition of a tank', 'extend.outbuilding.tank'),
  ('addition of a porch', 'extend.porch'),
  ('addition of a front porch', 'extend.porch.front'),
  ('addition of a side porch', 'extend.porch.side'),
  ('addition of a rear porch', 'extend.porch.rear'),
  ('new home/s', 'new.residential.dwelling'),
  ('new flat/s', 'new.residential.dwelling.flat'),
  ('new houses/s', 'new.residential.dwelling.house'),
  ('new office premises', 'new.office'),
  ('new storage or distribution premises', 'new.storage'),
  ('new industrial premises', 'new.industrial'),
  ('new retail premises', 'new.retail'),
  ('new leisure premises', 'new.leisure'),
  ('new mixed premises', 'new.mixed'),
  ('new agricultural premises', 'new.agriculture'),
  ('new agricultural premises', 'new.agriculture.glasshouse'),
  ('new agricultural premises', 'new.agriculture.poultry'),
  ('new agricultural premises', 'new.agriculture.pigs'),
  ('new agricultural premises', 'new.agricultural.mining '),
  ('new agricultural premises', 'new.agricultural.fish'),
  ('new forestry premises', 'new.forestry'),
  ('new other premises', 'new'),
  ('change of use', 'changeOfUse.whole'),
  ('changing the use of part of the property', 'changeOfUse.part'),
  ('permanent change of use', 'changeOfUse.permanent'),
  ('temporary change of use', 'changeOfUse.temporary'),
  ('temporary change of use - markets', 'changeOfUse.temporary.market'),
  ('temporary change of use - motor racing', 'changeOfUse.temporary.motorracing'),
  ('conversion of an outbuilding', 'changeOfUse.outbuilding'),
  ('convertion of an extension', 'changeOfUse.extension'),
  ('working from home', 'changeOfUse.workFromHome'),
  ('let a property', 'changeOfUse.let.whole'),
  ('let part of a property', 'changeOfUse.let.part'),
  ('siting of a caravan', 'changeOfUse.caravans'),
  ('land swap', 'changeOfUse.swap'),
  ('creation of a residential annexe', 'changeofUse.annexe'),
  ('subdivision of a property', 'unit.subdivide'),
  ('merge two or more properties', 'unit.merge'),
  ('other changes', 'other');
