import ErrorOutline from "@mui/icons-material/ErrorOutline";
import Typography from "@mui/material/Typography";
import { SendIntegration } from "@opensystemslab/planx-core/types";
import axios, { AxiosResponse } from "axios";
import DelayedLoadingIndicator from "components/DelayedLoadingIndicator/DelayedLoadingIndicator";
import { useStore } from "pages/FlowEditor/lib/store";
import React, { useEffect } from "react";
import { useAsync } from "react-use";
import { AsyncState } from "react-use/lib/useAsyncFn";

import Card from "../shared/Preview/Card";
import { WarningContainer } from "../shared/Preview/WarningContainer";
import { PublicProps } from "../shared/types";
import { DEFAULT_DESTINATION, getCombinedEventsPayload, Send } from "./model";

/** Response returned by /create-send-events endpoint */
type SendResponse = Record<SendIntegration, { event_id: string }>;

/** State generated by useAsync to hold SendResponse */
type SendRequestState = AsyncState<AxiosResponse<SendResponse>>;

export type Props = PublicProps<Send>;

const SendComponent: React.FC<Props> = ({
  destinations = [DEFAULT_DESTINATION],
  ...props
}) => {
  const fullProps = { destinations: destinations, ...props };
  if (
    window.location.pathname.endsWith("/draft") ||
    window.location.pathname.endsWith("/preview")
  ) {
    return <SkipSendWarning {...fullProps} />;
  } else {
    return <CreateSendEvents {...fullProps} />;
  }
};

/**
 * Skip queuing up Send events on non-Save&Return layout routes because they don't record lowcal_session data
 */
const SkipSendWarning: React.FC<Props> = (props) => (
  <Card handleSubmit={props.handleSubmit}>
    <WarningContainer>
      <ErrorOutline />
      <Typography variant="body1" ml={2}>
        You can only test submissions on <strong>published routes</strong> where
        Save & Return is enabled. Click "Continue" to finish reviewing content
        and skip submission.
      </Typography>
    </WarningContainer>
  </Card>
);

const CreateSendEvents: React.FC<Props> = ({
  destinations = [DEFAULT_DESTINATION],
  ...props
}) => {
  const [passport, sessionId, teamSlug] = useStore((state) => [
    state.computePassport(),
    state.sessionId,
    state.teamSlug,
  ]);

  // Send makes a single request to create scheduled events in Hasura, then those events make the actual submission requests with retries etc
  const url = `${
    import.meta.env.VITE_APP_API_URL
  }/create-send-events/${sessionId}`;
  const { loading, error, value }: SendRequestState = useAsync(async () => {
    const combinedEventsPayload = getCombinedEventsPayload({
      destinations,
      teamSlug,
      passport,
      sessionId,
    });

    return axios.post(url, combinedEventsPayload);
  });

  useEffect(() => {
    const isReady = !loading && !error && value;
    if (!isReady) return;

    // Construct breadcrumb containing IDs of each send event generated
    const data = Object.fromEntries(
      destinations.map((destination) => [
        `${destination}SendEventId`,
        value.data[destination]?.event_id,
      ]),
    );

    props.handleSubmit && props?.handleSubmit({ data });
  }, [loading, error, value, destinations, props]);

  // Throw errors so that they're caught by our error boundaries and Airbrake
  if (error) throw error;

  if (loading) {
    return (
      <Card>
        <DelayedLoadingIndicator text={"Submitting your application..."} />
      </Card>
    );
  }

  return (
    <Card>
      <DelayedLoadingIndicator text="Finalising your submission..." />
    </Card>
  );
};

export default SendComponent;
