version: "3.8"

services:
  # see https://github.com/Thiht/smocker
  mock-server:
    image: thiht/smocker
    restart: always
    ports:
      - 8080:8080
      - 8081:8081

  test-ready:
    image: alpine:3.17
    restart: unless-stopped
    depends_on:
      mock-server:
        condition: service_started
      minio:
        condition: service_healthy
      sharedb:
        condition: service_started
      api:
        condition: service_healthy
    entrypoint: sh
    command: -c "echo ready for testing"
