services:
  seed-database:
    platform: linux/amd64
    image: postgis/postgis:16-3.5
    volumes:
      - "./scripts/seed-database:/app"
    working_dir: "/app"
    entrypoint: "./container.sh postgres://${PG_USERNAME}:${PG_PASSWORD}@postgres/${PG_DATABASE} ${PRODUCTION_PG_URL_FOR_USER_GITHUB_ACTIONS}"
    command: "no_reset"
    restart: "no"
    depends_on:
      hasura-proxy:
        condition: service_healthy
