version: "3.8"

services:
  postgres:
    labels:
      virtual.host: postgres.${ROOT_DOMAIN}
      virtual.port: 5432
      virtual.tls: ${TLS_EMAIL}

  hasura:
    labels:
      virtual.host: hasura.${ROOT_DOMAIN}
      virtual.port: 8080
      virtual.tls: ${TLS_EMAIL}

  api:
    labels:
      virtual.host: api.${ROOT_DOMAIN}
      virtual.port: ${API_PORT}
      virtual.tls: ${TLS_EMAIL}

  sharedb:
    labels:
      virtual.host: sharedb.${ROOT_DOMAIN}
      virtual.port: 8000
      virtual.tls: ${TLS_EMAIL}

  minio:
    labels:
      virtual.host: minio.${ROOT_DOMAIN}
      virtual.port: 9000
      virtual.tls: ${TLS_EMAIL}

  editor:
    restart: unless-stopped
    build:
      context: ./editor.planx.uk
    ports:
      - 8043:8043
    volumes:
      - "./editor.planx.uk:/editor"
      - "/editor/node_modules"
    environment:
      REACT_APP_API_URL: https://api.${ROOT_DOMAIN}
      REACT_APP_HASURA_URL: https://hasura.${ROOT_DOMAIN}/v1/graphql
      REACT_APP_SHAREDB_URL: wss://sharedb.${ROOT_DOMAIN}
    labels:
      virtual.host: ${ROOT_DOMAIN}
      virtual.port: 8043
      virtual.tls: ${TLS_EMAIL}

  caddy-gen:
    image: wemakeservices/caddy-gen:latest
    container_name: caddy-gen
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy_data:/data/caddy # to back up certificates
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy_data:
  caddy_config:
