services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    platform: linux/amd64
    build:
      target: production
    volumes:
      - "/api/node_modules"
      - "/api/dist"
    environment:
      NODE_ENV: "pizza"
      AIRBRAKE_PROJECT_ID: ${AIRBRAKE_PROJECT_ID}
      AIRBRAKE_PROJECT_KEY: ${AIRBRAKE_PROJECT_KEY}

  sharedb:
    platform: linux/amd64

  hasura:
    platform: linux/amd64

  hasura-proxy:
    platform: linux/amd64

  editor:
    platform: linux/amd64
    container_name: editor
    image: pierrezemb/gostatic
    volumes:
      - ./apps/editor.planx.uk/build:/srv/http
    entrypoint: "/goStatic -fallback /index.html"

  localplanning:
    platform: linux/amd64
    container_name: localplanning
    image: pierrezemb/gostatic
    volumes:
      - ./apps/localplanning.services/dist:/srv/http
    entrypoint: "/goStatic -fallback /404.html"

  storybook:
    platform: linux/amd64
    container_name: storybook
    image: pierrezemb/gostatic
    volumes:
      - ./apps/editor.planx.uk/build/storybook:/srv/http
    entrypoint: "/goStatic -port 8044 -fallback /index.html"

  caddy:
    platform: linux/amd64
    image: lhr.vultrcr.com/planx/caddy-vultr:latest
    # default to pulling image from private Vultr registry (if not available)
    pull_policy: missing
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./ci/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data  # certs + keys
      - caddy_config:/config  # autosaved JSON config
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    environment:
      - TLS_EMAIL=${TLS_EMAIL}
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - VULTR_API_KEY=${VULTR_API_KEY}
      - API_PORT=${API_PORT}
      - HASURA_PROXY_PORT=${HASURA_PROXY_PORT}
      - PG_PORT=${PG_PORT}
      - SHAREDB_PORT=${SHAREDB_PORT}

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
