version: "3.8"

services:
  seed-database:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - "./scripts/seed-database:/app"
    working_dir: "/app"
    entrypoint: "./container.sh postgres://${PG_USERNAME}:${PG_PASSWORD}@postgres/${PG_DATABASE} ${PRODUCTION_PG_URL_FOR_USER_GITHUB_ACTIONS}"
    command: "no_reset include_published_flows"
    restart: "no"
    depends_on:
      hasura-proxy:
        condition: service_healthy
