packages:
  - 'apps/*'
  - 'apps/hasura.planx.uk/tests'
  - 'packages/*'
  - 'e2e'
  - 'e2e/tests/ui-driven'
  - 'e2e/tests/api-driven'
  - 'infrastructure/*'
  - 'scripts/*'
  
minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - dompurify@3.4.11
  - '@opensystemslab/map@1.0.0-alpha.14'

catalogs:
  infrastructure:
    '@pulumi/aws': ^7.24.0
    '@pulumi/awsx': ^3.4.0
    '@pulumi/cloudflare': ^6.14.0
    '@pulumi/postgresql': ^3.16.2
    '@pulumi/pulumi': ^3.229.0
    '@types/node': ~24.10.15
    typescript: ~5.9.3
