config:
  application:ai-gateway-api-key:
    secure: AAABAOo++Y1y8yUvYCFbMuROIimycuheH4oSRpRfj3wTCIKEgOlbPLjXKU4suUiiw4kOzWnJ4TkfNPG0sW8/a37lK4kJMMX9oVM5/4xCcI/9JdxS2dVnMOARzKQ=
  application:airbrake-project-id:
    secure: AAABAE+ZtQZO26XlmfAS7tG1DkwQ+G5OP82Roe4EOuk/tG1bMsI=
  application:airbrake-project-key:
    secure: AAABAMykToEvR6LGE6kUIjNeKfV/MsLtGq1Uv8dk6wAHp5og8/UIFF7yoo8rAZX5brx08nUnqwqrDrS8/I16+g==
  application:api-cpu: "4096"
  application:api-memory: "8192"
  application:cloudflare-zone-id:
    secure: AAABAMvLmULFOFiKvka1nnX/mMlFocCVlBtBXrXuJbkdJeS1xKRxloKX10LYMoScqaMHSNlFSAMA6SeWFkm4Pw==
  application:db-host:
    secure: AAABALfLAhFMoAzqQcMbG+83I3fc7KMpJ69QWeHJJrW+vdB9B5zwTeE8zruM4u2x3DsHwPZzb10GKsn0YP8RVHF2my9Pfq6uiTCWEI6Cr3uoRK0=
  application:db-password:
    secure: AAABALKR0YiXRR+Ja4giNfhqDPi5elXyjsuh5wy537BxW18O9N95rqGHwO5d+doPzgxS30N1G38=
  application:db-url:
    secure: AAABADikgxQsKaFgnsvx8YPBM2fFGrz8F6m5gMd3agb6ldEHySEDYgqhZCYypyfJaNpnSlFTPEdZ/Ze5fETzg496j3D7hHGe/Q7bM1A557EVbFHIfdGDAjPtgL2dXvNPY6hlw84GIUZuKHg5fqItVUJSIZWthSeIlTLHHqUpUuZJp+6L4le/HcgNRMkr8t5QuPSvBw==
  application:encryption-key:
    secure: AAABAGbTpoRtazwoNFNmaPCW0RdeTqjhEzQuYR1kl4ft7EWNxqswAu8Dc9T+YBxkYr3uaHbu5obzyo8I4QuVgg==
  application:enforce-scan-from:
    secure: AAABAERqq1ix/30HQGpkErGYiKW0bHSceUQxl5AynUazmIG0VcAeqf+phxcvmhzVjO3pYbjvvZI=
  application:file-api-key:
    secure: AAABAGyTfLujGho+V0tEhFXQRET5FjYK6txyaFTB3gY/VaKzq8yNlocJTAM5nt8mBhF6T+AeQD2GxW63
  application:file-api-key-barnet:
    secure: AAABANMl+fVFsRVGXvJV/aLManXO+TldXVDhp5QH6KGWJoG7O9Ket63zIW1iOiinINWJ2I5OizI=
  application:file-api-key-camden:
    secure: AAABAIybI+9gcWmqd9c1Nn2eKK9zwTzZKI9Fh09crqt2mxPFoEeHccBzNmXt6iHQRPnPI2/kvVg=
  application:file-api-key-doncaster:
    secure: AAABANsIFFm3IsQKbZHe4lEZGsJv3bcK2XOVzd6IiKj+4i/eiILIc7BS0KDQxqLskQ6QCv1sDw04pie8cvAlKqVYWBGmomA2
  application:file-api-key-epsom-ewell:
    secure: AAABANvwhiVRBq8NH7ZqcToUzYn4X+KfC5Wm8WjWUKXT5TuVXqC6zHhVVKFBbmdtKjC4j5M4+bWsLiFO9dO0MLobxLpK7YCE
  application:file-api-key-gateshead:
    secure: AAABAIIeEiX2htVth4Obb5JMQ3fcezHG/utwUsPikaLNmX+rSmMpGQgcG3LM1pN7XDeaO8J/eZHMilG5OvxGyz7Yo+RxVZV0
  application:file-api-key-gloucester:
    secure: AAABADXXkyrzbTU7FroS71nVLEGH2rQI63hqcAnm2hLdZYnTEJs/bcUPJU7t/hx1HY5qEmFKpKKhhiO3v5QVXUhwqO0C6BaD
  application:file-api-key-lambeth:
    secure: AAABAMNhdCTlFx3fZH/nO71ildypZB2JR5NixlQCENsS1VqwdiOX17q/Gi1UFrCQi2qaY2sZFG4=
  application:file-api-key-medway:
    secure: AAABABXSnk3j06JukiZ2u/me+pnRjHWAm+rf9FW9bSmzMfr9SWSKyN4XlltOYv1iZKujgI9hGIGiVR40+uYjGjy7BwNqOFxI
  application:file-api-key-nexus:
    secure: AAABAB2cv4GAf8RqN1hHbRbO68p8o4kLJYWsip9BoPdobrNtQB787M3s+gJnKKl9DfyXRHOXHGc=
  application:file-api-key-southwark:
    secure: AAABAL5G2cNl6XIQA0vcP6El4Us7Vk8Cz9JViRon25crc8MC0ix4ox2mE+XawsxYbLRwGfaRIJo=
  application:file-api-key-tewkesbury:
    secure: AAABAA1cz4BbfrTaXhcERQD0MaMSky0fC6ej9/N0n1IBB2w4iBd3S2hNi0T39VEiAB6CNouB+yElaoR7ZWg1xaIIJX2K6TGl
  application:google-client-id: 987324067365-vpsk3kgeq5n32ihjn760ihf8l7m5rhh8.apps.googleusercontent.com
  application:google-client-secret:
    secure: AAABAN5E+De3A3HtpLVaSNTDwk9Uz4r2d5g8SIRVbNOd2fj3eU+lGJXjVbEAnxezr14hwabbfwW2ptjcFzqkhG7OmQ==
  application:govuk-notify-api-key:
    secure: AAABAGnNAydaUYfiP0CZg1hctj1cHvR000SMEwNhycjohmbeWC+KCRc37ns9FkcbfWlnCvabr9MvtRT9YSTtUb4W/b8lDsMtsFQ2cgq4ewVpIiyFFC3ICrc0vA5WpbIIeCDs4mRiHIlKr0AAWAGF4KuECMYmWRuO3uVE7w==
  application:hasura-admin-secret:
    secure: AAABAI+T8RFROAmmTg7ahXUuUX/85OcJ47pVKetKKoVjQklpXjvKE6mUc/wDcjIbA330+XoWufw=
  application:hasura-cpu: "2048"
  application:hasura-memory: "4096"
  application:hasura-planx-api-key:
    secure: AAABAExsXFL7HabeK0Z1oSUJzI2NqVqEmKJ1ojYXyX4Hi8Sbt1Ht9QJc/Yn3cPBAB2r32HKa4HtqqLmfGjS+04lFB/I=
  application:hasura-proxy-cpu: "512"
  application:hasura-proxy-memory: "1024"
  application:hasura-service-scaling-maximum: "4"
  application:hasura-service-scaling-minimum: "1"
  application:idox-nexus-client:
    secure: AAABACdm6IyRjfVPrHLCS5eKQD0ixA2lFC5h04HULwcCXx3j
  application:idox-nexus-submission-url: todo
  application:idox-nexus-token-url: todo
  application:jwt-secret:
    secure: AAABAEGWTi+vTHnjkJfyJQneZIz1aDoplF4y3/sLFnAKuvDcP/80/7ReX3W4wiKWuHMygSxKY5y2PImYJjZ9YbSZMP9d7NtD
  application:lambda-nodejs-runtime: nodejs24.x
  application:lps-cloudflare-zone-id:
    secure: AAABAH+7QupNP8cRQRnFKSufAxT0Fd3BpC2rMnamjDNfPCJfJZ68AJ4CtE6Rc2ZNF9olgrF6zzsH2nzj2wNdzg==
  application:lps-domain: localplanning.services
  application:mapbox-access-token:
    secure: AAABAGwrLOkFpIZ3u8XeKIsfk1ujqFYKdv4us+ia2EdCXU8sBj2LiXfn8K6UcOifzf3HlOA6CYL3WwalKLmtvuq90CInbipB3dtY4Mr2Vx7NcUA7zxbUtli+8WcShIiNq490GwlTlf7ChjnNSIr3FzCeK3D/Xiq25wT0398c5ZwHyg==
  application:mb-db-connection-uri:
    secure: AAABAFxCleouG7pLLASpxso/YVGiTOn23PdFvK3iSJ4ak9rc6ryCTWyNlnh1+jlR5NOPJ0TUhVZX6EpW0ufFGDtMXCA8KoqGnW4MujbyqJrEyoznoV0FObIzzGCIWiocww+VVpkACrOFHAurcotGeICxwXJpstg04U2s6x5/eoA7RwWuAIoV2dnrcBZklCIeRuXjuyAZ
  application:metabase-api-key:
    secure: AAABAAdkLyFGZJ50HENSAkvYZ9Y3Qj2oKysmBKNWbqgcCLYz+dDvgEBPTbzG6lNgOqUyySJDmquMilyiUtTLau7rpF4txEM/O4DHmAinVg==
  application:metabase-cpu: "1024"
  application:metabase-encryption-secret-key:
    secure: AAABAKQ6L5aOwZWpj9YOsaW8bOOukjt1mZuTgdKjM/3nSmF/0nM/f9c9W9DXygUFj2wtq5/iugo1UTS0+bhEn8Dr9k1Qzr2EmuGpQw==
  application:metabase-memory: "2048"
  application:metabasePgPassword:
    secure: AAABANcFdBY/ydhdJaCIuGqFrXzSUIgHylDFK9nd+7y+PmIiIL879QO1p6Hp7NNOmPEWcdrVHwg=
  application:microsoft-client-id:
    secure: AAABAGm0SUnS8I54uBHI+Y0F1hMk8WSSKO1n+b52MCaYU8aGlbtsEuccJiQ8WXf7IFwWWgoBIeVPdk0eIGENHUet0HA=
  application:microsoft-client-secret:
    secure: AAABADAL9YkrUfJaDga7MaVRD/dZaElsnFnnC+7IvqqlgBFywXFwVKnSMbVZ1SMFoitG8C6bKHhl2BPwOHcuvkzMKblwYzvu
  application:ordnance-survey-api-key:
    secure: AAABANmVR/iyxoja6JGBOBjhlijbMiqdqpNRwqS2p+ZusuwiYdKBACIi5y/vi2HMg7+ydXWR0SPVqtQuK5O/tA==
  application:resend-from-address: noreply@notifications.planx.uk
  application:resend-api-key:
    secure: AAABAGl5L3MjVaGcm6xCnQeGpoBflVREcAielFkw1CSGs7dfeQJoU41d30Br/QVTkrn8dk/dr6IVavqT3Cbtq07jGuI=
  application:session-secret:
    secure: AAABACeZpncVIdwarlb/J9qtaPqUob0YwbaOVDNEgfhSJ71aq0pkZml1EP+JqMKvyhkG483LcIiGzEh/ZDJehMu2
  application:sharedb-cpu: "512"
  application:sharedb-memory: "1024"
  application:skip-rate-limit-secret:
    secure: AAABADPv0Fp55IK8xL0Kxx/Kq2sFeRIgbKn0sgHBFhTsWh09kV3/OyG0d/wkE3zm+15zbud0GR4TSl4z//MV5XgxLWDhJgGJ
  application:slack-internal-errors-webhook:
    secure: AAABAIdznmeJ53lLUde2j8a7FeSlBO7UpdQNRWWxErp7djbuAk3YdAIH2zK1qmz5nfFT8fRLh/RenS/bFHAW4/KsCjziio1JlDIy7YsnxOBsL6ZE+pUlzM6/SlMcZth/S/4FKVfv7FxwmK9boG8pCSoAbJx0GCCpXQ==
  application:slack-webhook-url:
    secure: AAABANpjl5NnZcSFTUB3iHS4qsQuSgHGkki0yYn/LEB9Oq6kqg/RFSvwl6toXoLjgKRwhcguba8Qyp/gA+nCSMyFu7i36QVFiTRjPFsoQ9esTEo/zGqyNf2tCL/AFd+oE2/WLo1TSq7/Qt7hVm49
  application:uniform-client-buckinghamshire:
    secure: AAABAPZoWkQqJrWdBApvOh8gWFES7HE7Ebm7YcoOaCbIl8Ru9uOlK2SfafzxCs5Rty93RJ76u5ATnAyEws8=
  application:uniform-client-lambeth:
    secure: AAABAJprpAkhAJI6w1pmdHm7qpcwKJKVPq/2EwS23LEuZ0TTATSPcT24dUObow0mw6LweTifCqXOX/CfTA==
  application:uniform-client-southwark:
    secure: AAABAPU5mofUcMemIN579HhHs8LVwH/ikqLTUinpj1qNmmesfZUBKRrPUUtTuqJ7B0YDnxNB8uZb8UkGy5y8
  application:uniform-submission-url: https://identity.idoxgroup.com/agw/submission-api
  application:uniform-token-url: https://identity.idoxgroup.com/uaa/oauth/token
  cloudflare:apiToken:
    secure: AAABAMbIBX9N21ModHyDYCQCGZXkRUP62NIUMhsxkK+/YUPRQr6PEqgZX9LRP2UuVwvVHd2RxvKGT8lpq8oAgyeDYP1eZSUl
  application:stripe-secret-key:
    secure: AAABAJdkS0v68Q8Vr2V7tLSb74ALGCTpjLOG2W6ZTgwb5aRUZkrNRUnv3dL4pdw85YxxOI6KUJnT30cGJyim4A==
  application:stripe-connect-client-id:
    secure: AAABAEGQOw44bXhdtDjhJiZVF3HPz8ZAkhH6aw6PCj3y7Vz1bBpyVDgaWiLsmt9h+R8S/3a9XZgnubQgvO9kiRh8Cg==
  application:stripe-webhook-secret:
    secure: AAABAGr/VtVQykWP+59NpEdGASf1nqLP4jHGiS43QHbwp0O61VdwVApd5h87ww==
