table:
  name: email_applications
  schema: public
insert_permissions:
  - role: api
    permission:
      check: {}
      columns:
        - id
        - request
        - response
        - recipient
        - team_slug
        - created_at
        - sanitised_at
        - session_id
select_permissions:
  - role: api
    permission:
      columns:
        - id
        - request
        - response
        - recipient
        - team_slug
        - created_at
        - sanitised_at
        - session_id
      filter: {}
update_permissions:
  - role: api
    permission:
      columns:
        - id
        - request
        - response
        - recipient
        - team_slug
        - created_at
        - sanitised_at
        - session_id
      filter: {}
      check: {}
event_triggers:
  - name: setup_email_applications_notifications
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 30
      num_retries: 1
      timeout_sec: 60
    webhook_from_env: HASURA_PLANX_API_URL
    headers:
      - name: authorization
        value_from_env: HASURA_PLANX_API_KEY
    request_transform:
      method: POST
      query_params:
        type: email-submission
      template_engine: Kriti
      url: '{{$base_url}}/webhooks/hasura/send-slack-notification'
      version: 2
