import { Feature, Point, Polygon } from "geojson";
import { act } from "react-dom/test-utils";

/**
 * Helper to mock a user's interaction with the @opensystemslab/map element
 * We aren't able to mock a user's click interaction, so instead we dispatch an event which matches the one generated by the webcomponent
 */
export const addFeaturesToMap = async (
  map: HTMLElement,
  features: Feature<Point | Polygon, { label: string }>[],
) => {
  const mockEvent = new CustomEvent("geojsonChange", {
    detail: {
      "EPSG:3857": { features },
    },
  });
  act(() => map.dispatchEvent(mockEvent));
};
