import { screen } from "@testing-library/react";
import { Feature, Point, Polygon } from "geojson";
import { act } from "react-dom/test-utils";

/**
 * Helper to mock a user's interaction with the @opensystemslab/map element
 * We aren't able to mock a user's click interaction, so instead we dispatch an event which matches the one generated by the webcomponent
 */
export const addFeaturesToMap = async (
  map: HTMLElement,
  features: Feature<Point | Polygon, { label: string }>[],
) => {
  const mockEvent = new CustomEvent("geojsonChange", {
    detail: {
      "EPSG:3857": { features },
    },
  });
  act(() => map.dispatchEvent(mockEvent));
};

export const addMultipleFeatures = (
  featureArray: Feature<Point, { label: string }>[],
) => {
  const map = screen.getByTestId("map-and-label-map");
  const pointsAddedArray: Feature<Point, { label: string }>[] = [];
  featureArray.forEach((feature) => {
    pointsAddedArray.push(feature);
    addFeaturesToMap(map, pointsAddedArray);
  });
};
