openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0
tags:
  - name: gis
paths:
  /lpa:
    get:
      summary: Get LPAs at a given lat/lon
      description: Retrieves the Local Planning Authorities whose boundaries intersect a given point
      parameters:
        - in: query
          name: lon
          required: true
          description: Longitude of the intersecting point
        - in: query
          name: lat
          required: true
          description: Latitude of the intersecting point
      responses:
        "200":
          description: A JSON array of Local Planning Authorities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
