name: Setup Node and pnpm
description: Install pnpm, set up Node with pnpm cache, and apply .gitconfig

inputs:
  node-version:
    description: The Node.js version to use
    required: false
    default: 24.14.0
  pnpm-version:
    description: The pnpm version to use
    required: false
    default: 10.30.2
  cache:
    description: setup-node cache strategy
    required: false
    default: "pnpm"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v5.0.0
      with:
        version: ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: "**/pnpm-lock.yaml"
        
    - name: Setup .gitconfig
      shell: bash
      run: mv .gitconfig ~/.gitconfig