import { ComponentType } from "@opensystemslab/planx-core/types";

export const COMPONENT_TITLES: Partial<Record<ComponentType, string>> = {
  [ComponentType.AddressInput]: "Address input",
  [ComponentType.Calculate]: "Calculate",
  [ComponentType.Checklist]: "Checklist",
  [ComponentType.Confirmation]: "Confirmation",
  [ComponentType.ContactInput]: "Contact input",
  [ComponentType.Content]: "Content",
  [ComponentType.DateInput]: "Date input",
  [ComponentType.DrawBoundary]: "Draw boundary",
  [ComponentType.EnhancedTextInput]: "Text input",
  [ComponentType.ExternalPortal]: "Flow",
  [ComponentType.Feedback]: "Feedback",
  [ComponentType.FileUpload]: "File upload",
  [ComponentType.FileUploadAndLabel]: "Upload and label",
  [ComponentType.Filter]: "Filter",
  [ComponentType.FindProperty]: "Find property",
  [ComponentType.InternalPortal]: "Folder",
  [ComponentType.List]: "List",
  [ComponentType.MapAndLabel]: "Map and label",
  [ComponentType.NextSteps]: "Next steps",
  [ComponentType.Notice]: "Notice",
  [ComponentType.NumberInput]: "Number input",
  [ComponentType.Page]: "Page",
  [ComponentType.Pay]: "Pay",
  [ComponentType.PlanningConstraints]: "Planning constraints",
  [ComponentType.PropertyInformation]: "Property information",
  [ComponentType.Question]: "Question",
  [ComponentType.ResponsiveChecklist]: "Responsive checklist",
  [ComponentType.ResponsiveQuestion]: "Responsive question",
  [ComponentType.Result]: "Result",
  [ComponentType.Review]: "Review",
  [ComponentType.Section]: "Section",
  [ComponentType.Send]: "Send",
  [ComponentType.SetFee]: "Set fees",
  [ComponentType.SetValue]: "Set value",
  [ComponentType.TaskList]: "Task list",
  [ComponentType.TextInput]: "Text input",
};
