import { ComponentType as TYPES } from "@opensystemslab/planx-core/types";
import {
  IconAlertTriangle,
  IconArrowRight,
  IconArrowsSplit,
  IconArrowsSplit2,
  IconArticle,
  IconBrowserCheck,
  IconCalendarEvent,
  IconCheckupList,
  IconCloudUpload,
  IconCreditCard,
  IconCurrencyPound,
  IconFilter,
  IconFolder,
  IconHome,
  IconId,
  IconLayoutList,
  IconList,
  IconListCheck,
  IconListDetails,
  IconMap,
  IconMapPin,
  IconMathFunction,
  IconMessage,
  IconNote,
  IconNumber123,
  IconPencil,
  IconPlaylistAdd,
  IconRulerMeasure,
  IconSearch,
  IconSend,
  IconShape,
  IconSitemap,
  IconSparkles,
  IconSquareCheck,
  IconTypography,
} from "@tabler/icons-react";
import type { TablerIcon } from "ui/icons/Icon";

export const ICONS: {
  [key in TYPES]: TablerIcon | undefined;
} = {
  [TYPES.AddressInput]: IconHome,
  [TYPES.Answer]: undefined,
  [TYPES.Calculate]: IconMathFunction,
  [TYPES.Checklist]: IconSquareCheck,
  [TYPES.Confirmation]: IconBrowserCheck,
  [TYPES.ContactInput]: IconId,
  [TYPES.Content]: IconTypography,
  [TYPES.DateInput]: IconCalendarEvent,
  [TYPES.DrawBoundary]: IconRulerMeasure,
  [TYPES.EnhancedTextInput]: IconSparkles,
  [TYPES.ExternalPortal]: IconSitemap,
  [TYPES.Feedback]: IconMessage,
  [TYPES.FileUpload]: IconCloudUpload,
  [TYPES.FileUploadAndLabel]: IconCloudUpload,
  [TYPES.Filter]: IconFilter,
  [TYPES.FindProperty]: IconSearch,
  [TYPES.Flow]: undefined,
  [TYPES.InternalPortal]: IconFolder,
  [TYPES.List]: IconLayoutList,
  [TYPES.MapAndLabel]: IconShape,
  [TYPES.NextSteps]: IconArrowRight,
  [TYPES.Note]: IconNote,
  [TYPES.Notice]: IconAlertTriangle,
  [TYPES.NumberInput]: IconNumber123,
  [TYPES.Page]: IconArticle,
  [TYPES.Pay]: IconCreditCard,
  [TYPES.PlanningConstraints]: IconMap,
  [TYPES.PropertyInformation]: IconMapPin,
  [TYPES.Question]: IconArrowsSplit2,
  [TYPES.ResponsiveChecklist]: IconSquareCheck,
  [TYPES.ResponsiveQuestion]: IconArrowsSplit,
  [TYPES.Result]: IconListCheck,
  [TYPES.Review]: IconCheckupList,
  [TYPES.Section]: IconList,
  [TYPES.Send]: IconSend,
  [TYPES.SetFee]: IconCurrencyPound,
  [TYPES.SetValue]: IconPlaylistAdd,
  [TYPES.TaskList]: IconListDetails,
  [TYPES.TextInput]: IconPencil,
} as const;
