import { AdminPanelData } from "types";

export const mockTeams: AdminPanelData[] = [
  {
    id: "1",
    name: "Barking and Dagenham",
    slug: "barking",
    referenceCode: "BDD",
    liveFlows: [
      "Find out if you need planning permission",
      "Apply for prior approval",
      "Barking draft 2",
    ],
    planningDataEnabled: false,
    govpayEnabled: true,
    logo: undefined,
    favicon: undefined,
    primaryColour: "#000000",
    linkColour: "#000000",
    actionColour: "#000000",
    homepage: undefined,
    subdomain: undefined,
    article4sEnabled: "@todo",
    govnotifyPersonalisation: {
      helpEmail: "example@council.co.uk",
      helpPhone: "(01234) 567890",
      emailReplyToId: "727d48fa-cb8a-42f9-b8b2-55032f3bb451",
      helpOpeningHours: "Monday - Friday, 9am - 5pm",
    },
    powerAutomateEnabled: false,
    sendToEmailAddress: undefined,
    bopsSubmissionURL: undefined,
  },
  {
    id: "2",
    name: "Doncaster",
    referenceCode: "DON",
    liveFlows: [
      "Notify completion of planning application",
      "Find out if you need planning permission",
      "apply for prior approval ",
      "Apply for service declarations",
      "Article4",
    ],
    planningDataEnabled: true,
    govpayEnabled: true,
    logo: "https://path.to.logo.com/theopensystemslab/planx-team-logos/main/logo.svg",
    slug: "doncaster",
    article4sEnabled: "@todo",
    powerAutomateEnabled: false,
  },
  {
    id: "3",
    name: "Newcastle",
    referenceCode: "NCL",
    liveFlows: [
      "Confirmation pages",
      "Find out if you need planning permission",
      "Listed building pre application advice",
      "Apply for prior approval",
      "Apply for service declarations",
      "Article4",
      "Apply for a lawful development certificate",
    ],
    planningDataEnabled: false,
    govpayEnabled: false,
    logo: "https://path.to.logo.com/theopensystemslab/planx-team-logos/main/logo.svg",
    slug: "newcastle",
    article4sEnabled: "@todo",
    powerAutomateEnabled: true,
  },
  {
    id: "4",
    name: "Tewkesbury",
    referenceCode: "TWK",
    liveFlows: [
      "Listed building pre application advice",
      "Apply for service declarations",
      "Article4",
      "Apply for a lawful development certificate",
    ],
    planningDataEnabled: false,
    govpayEnabled: true,
    logo: "https://path.to.logo.com/theopensystemslab/planx-team-logos/main/logo.svg",
    slug: "tewkesbury",
    article4sEnabled: "@todo",
    powerAutomateEnabled: false,
  },
];
