CREATE TABLE "public"."team_settings" ("id" serial NOT NULL, 
"team_id" integer NOT NULL, 
"reference_code" text, 
"homepage" text, 
"help_email" text NOT NULL DEFAULT 'example@council.gov.uk', 
"help_phone" text NOT NULL DEFAULT '(01234) 567890', 
"help_opening_hours" text NOT NULL DEFAULT 'Monday - Friday, 9am - 5pm', 
"email_reply_to_id" text NOT NULL DEFAULT '727d48fa-cb8a-42f9-b8b2-55032f3bb451', 
"has_planning_data" boolean NOT NULL DEFAULT False, 
"external_planning_site_url" text DEFAULT 'https://www.planningportal.co.uk/', 
"external_planning_site_name" text DEFAULT 'Planning Portal', 
"boundary_json" jsonb NOT NULL DEFAULT '{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[1.9134116, 49.528423], [1.9134116, 61.331151], [1.9134116, 61.331151], [-10.76418, 61.331151], [-10.76418, 49.528423]]]}, "properties": {}}'::jsonb, "boundary_url" text, 
PRIMARY KEY ("id") , 
FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON UPDATE cascade ON DELETE cascade, 
UNIQUE ("id"), UNIQUE ("team_id"), UNIQUE ("reference_code"));
COMMENT ON TABLE "public"."team_settings" IS E'Global settings for boundary and contact details';
