# FROM hasura/graphql-engine:v2.0.10.cli-migrations-v2
# FROM fedormelexin/graphql-engine-arm64:v1.3.3.cli-migrations-v2
FROM hasura/graphql-engine:v2.1.0-beta.3.cli-migrations-v2
WORKDIR /
COPY metadata hasura-metadata
COPY migrations hasura-migrations
