table:
  name: s3_applications
  schema: public
insert_permissions:
  - role: api
    permission:
      check: {}
      columns:
        - id
        - webhook_request
        - webhook_response
        - session_id
        - team_slug
        - created_at
    comment: ""
select_permissions:
  - role: api
    permission:
      columns:
        - id
        - webhook_request
        - webhook_response
        - session_id
        - team_slug
        - created_at
      filter: {}
    comment: ""
update_permissions:
  - role: api
    permission:
      columns:
        - id
        - webhook_request
        - webhook_response
        - session_id
        - team_slug
        - created_at
      filter: {}
      check: null
    comment: ""
event_triggers:
  - name: setup_s3_applications_notifications
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 30
      num_retries: 1
      timeout_sec: 60
    webhook: '{{HASURA_PLANX_API_URL}}'
    headers:
      - name: authorization
        value_from_env: HASURA_PLANX_API_KEY
    request_transform:
      method: POST
      query_params:
        type: s3-submission
      template_engine: Kriti
      url: '{{$base_url}}/webhooks/hasura/send-slack-notification'
      version: 2
