table:
  name: team_settings
  schema: public
object_relationships:
  - name: team
    using:
      foreign_key_constraint_on: team_id
insert_permissions:
  - role: platformAdmin
    permission:
      check: {}
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
    comment: ""
select_permissions:
  - role: api
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
      filter: {}
    comment: ""
  - role: demoUser
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
      filter: {}
    comment: ""
  - role: platformAdmin
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
      filter: {}
    comment: ""
  - role: public
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - team_id
      filter: {}
    comment: ""
  - role: teamAdmin
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
      filter: {}
    comment: ""
  - role: teamEditor
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
      filter: {}
    comment: ""
update_permissions:
  - role: platformAdmin
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - has_article4_schema
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - id
        - is_trial
        - reference_code
        - submission_email
        - team_id
      filter: {}
      check: null
    comment: ""
  - role: teamAdmin
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - reference_code
        - submission_email
      filter:
        team:
          members:
            _and:
              - user_id:
                  _eq: x-hasura-user-id
              - role:
                  _eq: teamEditor
      check: null
    comment: ""
  - role: teamEditor
    permission:
      columns:
        - boundary_bbox
        - boundary_url
        - email_reply_to_id
        - external_planning_site_name
        - external_planning_site_url
        - help_email
        - help_opening_hours
        - help_phone
        - homepage
        - reference_code
        - submission_email
      filter:
        team:
          members:
            _and:
              - user_id:
                  _eq: x-hasura-user-id
              - role:
                  _eq: teamEditor
      check: null
    comment: ""
