openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0
paths:
  /lpa:
    get:
      tags: ["gis"]
      summary: Get LPAs at a given lat/lon
      description: Retrieves the Local Planning Authorities whose boundaries intersect a given point
      parameters:
        - in: query
          name: lon
          required: true
          description: Longitude of the intersecting point
        - in: query
          name: lat
          required: true
          description: Latitude of the intersecting point
      responses:
        "200":
          description: A JSON array of Local Planning Authorities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /planning-constraints-schema:
    get:
      tags: ["gis"]
      summary: Get PlanX-supported data values for planning constraints
      description: Returns PlanX-supported data values for planning constraints in-service automations, including granular Article 4 values for applicable local authorities
      parameters:
        - in: query
          name: localAuthority
          required: false
          description: Local authority name, equivalent to PlanX team slug
      responses:
        "200":
          description: A JSON array of data values
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
