packages:
  - application
  - certificates
  - common
  - data
  - ml
  - networking

allowBuilds:
  '@pulumi/aws': true
  '@pulumi/cloudflare': true
  '@pulumi/docker': true
  '@pulumi/docker-build': true
  aws-sdk: true
  protobufjs: true
  tldjs: true

catalog:
  '@pulumi/aws': ^7.24.0
  '@pulumi/awsx': ^3.4.0
  '@pulumi/cloudflare': ^6.14.0
  '@pulumi/postgresql': ^3.16.2
  '@pulumi/pulumi': ^3.229.0
  '@types/node': ~24.10.15
  typescript: ~5.9.3

minimumReleaseAge: 10080

savePrefix: '~'

strictPeerDependencies: true
