-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."flows" add column "has_send_component" boolean
--  null default 'false';
