name = 'reverseproxy'
type = 'javascript'
usage_model = ''
workers_dev = true
compatibility_date = "2022-02-16"

[build]
command = "pnpm install && pnpm build"

[build.upload]
format = "service-worker"
