name: Jest

on: [push, pull_request]

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta

    - uses: pnpm/action-setup@v1.2.1

    - run: pnpm run test
