openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0

tags:
  - name: analytics
  - name: metabase

components:
  responses:
    AnalyticsResponse:
      description: Successful response with no content. Not awaited from server as endpoint is called via the Beacon API

  schemas:
    FilterDashboardLink:
      type: object
      properties:
        flowId:
          type: string
          description: ID of the flow
        teamId:
          type: number
          description: ID of the team
        serviceSlug:
          type: string
          description: Service slug identifier
      required:
        - flowId
        - teamId
        - serviceSlug

paths:
  /analytics/log-user-exit:
    post:
      summary: Log user exit
      description: Capture an analytic event which represents a user exiting a service
      tags:
        - analytics
      responses:
        "204":
          $ref: "#/components/responses/AnalyticsResponse"

  /analytics/log-user-resume:
    post:
      summary: Log user resume
      description: Capture an analytic event which represents a user resuming a service
      tags:
        - analytics
      responses:
        "204":
          $ref: "#/components/responses/AnalyticsResponse"
