openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0

tags:
  - name: analytics
  - name: metabase

components:
  responses:
    AnalyticsResponse:
      description: Successful response with no content. Not awaited from server as endpoint is called via the Beacon API

  schemas:
    NewCollection:
      type: object
      required:
        - slug
      properties:
        slug:
          type: string
          description: Name of the collection
        description:
          type: string
          description: Optional description for the collection
        parentId:
          type: integer
          description: Optional ID of the parent collection

paths:
  /analytics/log-user-exit:
    post:
      summary: Log user exit
      description: Capture an analytic event which represents a user exiting a service
      tags:
        - analytics
      responses:
        "204":
          $ref: "#/components/responses/AnalyticsResponse"

  /analytics/log-user-resume:
    post:
      summary: Log user resume
      description: Capture an analytic event which represents a user resuming a service
      tags:
        - analytics
      responses:
        "204":
          $ref: "#/components/responses/AnalyticsResponse"

  /metabase/collection:
    post:
      summary: Create new Metabase collection
      description: Creates a new collection in Metabase if it doesn't already exist
      tags:
        - metabase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCollection"
      responses:
        "201":
          description: Collection created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/NewCollection"
        "400":
          description: Bad request or collection creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
