openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0
tags:
  name: team
  description: Team and Team Member related requests
components:
  parameters:
    teamSlug:
      in: path
      name: teamSlug
      type: string
      required: true
  schemas:
    UpsertMember:
      type: object
      properties:
        userEmail:
          type: email
          example: einstein@princeton.edu
        role:
          type: string
          enum: ["teamViewer", "teamEditor"]
paths:
  /team/{teamSlug}/change-member-role:
    patch:
      summary: Change role of an existing team member
      description: "Requires authentication via a Cloudflare WARP client
        \n\n
        Please login at [https://api.editor.planx.uk/team](https://api.editor.planx.uk/team)"
      tags: ["team"]
      parameters:
        - $ref: "#/components/parameters/teamSlug"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertMember"
      responses:
        "200":
          $ref: "#/components/responses/SuccessMessage"
        "500":
          $ref: "#/components/responses/ErrorMessage"
  /team/{teamSlug}/remove-member:
    delete:
      summary: Remover user from team
      description: "Requires authentication via a Cloudflare WARP client
        \n\n
        Please login at [https://api.editor.planx.uk/team](https://api.editor.planx.uk/team)"
      tags: ["team"]
      parameters:
        - $ref: "#/components/parameters/teamSlug"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: email
                  example: einstein@princeton.edu
      responses:
        "200":
          $ref: "#/components/responses/SuccessMessage"
        "500":
          $ref: "#/components/responses/ErrorMessage"
