import { ComponentType as TYPES } from "@opensystemslab/planx-core/types";
import { PublicProps } from "@planx/components/shared/types";
import { FormikConfig, useFormik } from "formik";
import React from "react";

import { flatten } from "../List/utils";
import Card from "../shared/Preview/Card";
import { CardHeader } from "../shared/Preview/CardHeader/CardHeader";
import { useSchema } from "../shared/Schema/hook";
import { SchemaUserData } from "../shared/Schema/model";
import { SchemaFields } from "../shared/Schema/SchemaFields";
import { getRequestedFiles } from "../shared/Schema/utils";
import { getPreviouslySubmittedData, makeData } from "../shared/utils";
import { Page } from "./model";

type Props = PublicProps<Page>;

function PageComponent(props: Props) {
  const { formikConfig } = useSchema({
    schema: props.schema,
    previousValues: getPreviouslySubmittedData(props),
  });

  const onSubmit: FormikConfig<SchemaUserData>["onSubmit"] = (values) => {
    if (!props.handleSubmit) return;

    // Default data - used for "back", to maintain a copy of the data as generated by the component
    const defaultPassportData = makeData(props, values.schemaData)?.["data"];

    // Flattened data - used for access via automation, SetValue etc
    const flattenedData = flatten(defaultPassportData, {
      depth: 2,
      omitIndexKeys: true,
    });

    const requestedFiles = getRequestedFiles({
      schemaFn: props.fn,
      schema: props.schema,
      userData: values.schemaData,
      context: TYPES.Page,
    });

    const userData = {
      data: {
        ...defaultPassportData,
        ...flattenedData,
        ...requestedFiles,
      },
    };

    props.handleSubmit(userData);
  };

  const formik = useFormik({
    ...formikConfig,
    onSubmit,
  });

  return (
    <Card handleSubmit={formik.handleSubmit} isValid>
      <CardHeader {...props} />
      <SchemaFields
        formik={formik}
        schema={props.schema}
        sx={(theme) => ({
          display: "flex",
          flexDirection: "column",
          gap: theme.spacing(2),
        })}
      />
    </Card>
  );
}

export default PageComponent;
