import { PublicProps } from "@planx/components/shared/types";
import { FormikConfig, useFormik } from "formik";
import { useStore } from "pages/FlowEditor/lib/store";
import React from "react";

import { PASSPORT_REQUESTED_FILES_KEY } from "../FileUploadAndLabel/model";
import { flatten } from "../List/utils";
import Card from "../shared/Preview/Card";
import { CardHeader } from "../shared/Preview/CardHeader/CardHeader";
import { useSchema } from "../shared/Schema/hook";
import { SchemaUserData } from "../shared/Schema/model";
import { SchemaFields } from "../shared/Schema/SchemaFields";
import { getPreviouslySubmittedData, makeData } from "../shared/utils";
import { Page } from "./model";

type Props = PublicProps<Page>;

function PageComponent(props: Props) {
  const { formikConfig } = useSchema({
    schema: props.schema,
    previousValues: getPreviouslySubmittedData(props),
  });

  const { required, recommended, optional } = useStore
    .getState()
    .requestedFiles();

  const onSubmit: FormikConfig<SchemaUserData>["onSubmit"] = (values) => {
    if (!props.handleSubmit) return;

    // Default data - used for "back", to maintain a copy of the data as generated by the component
    const defaultPassportData = makeData(props, values.schemaData)?.["data"];

    // Flattened data - used for access via automation, SetValue etc
    const flattenedData = flatten(defaultPassportData, {
      depth: 2,
      omitIndexKeys: true,
    });

    // If schema contains FileUpload fields, update passport to include these as required fields
    const fileUploadFields = props.schema.fields.filter(
      ({ type, required }) => type === "fileUpload" && required,
    );
    const fileUploadDataValues = fileUploadFields.map(({ data }) => data.fn);

    const userData = {
      data: {
        ...defaultPassportData,
        ...flattenedData,
        [PASSPORT_REQUESTED_FILES_KEY]: {
          required: [...required, ...fileUploadDataValues],
          recommended,
          optional,
        },
      },
    };

    props.handleSubmit(userData);
  };

  const formik = useFormik({
    ...formikConfig,
    onSubmit,
  });

  return (
    <Card handleSubmit={formik.handleSubmit} isValid>
      <CardHeader {...props} />
      <SchemaFields
        formik={formik}
        schema={props.schema}
        sx={(theme) => ({
          display: "flex",
          flexDirection: "column",
          gap: theme.spacing(2),
        })}
      />
    </Card>
  );
}

export default PageComponent;
