import { PublicProps } from "@planx/components/sharedTypes";
import { FormikConfig, useFormik } from "formik";
import React from "react";

import { flatten } from "../List/utils";
import Card from "../shared/Preview/Card";
import { CardHeader } from "../shared/Preview/CardHeader/CardHeader";
import { useSchema } from "../shared/Schema/hook";
import { SchemaUserData } from "../shared/Schema/model";
import { SchemaFields } from "../shared/Schema/SchemaFields";
import { getPreviouslySubmittedData } from "../shared/utils";
import { Page } from "./model";

type Props = PublicProps<Page>;

function PageComponent(props: Props) {
  const { formikConfig } = useSchema({
    schema: props.schema,
    previousValues: getPreviouslySubmittedData(props),
  });

  const onSubmit: FormikConfig<SchemaUserData>["onSubmit"] = (data) => {
    if (!props.handleSubmit) return;

    // Default data - used for "back", to maintain a copy of the data as generated by the component
    const defaultPassportData = { [props.fn]: data.schemaData };

    // Flattened data - used for access via automation, SetValue etc
    const flattenedData = flatten({ [props.fn]: data.schemaData[0] });

    const userData = {
      data: {
        ...defaultPassportData,
        ...flattenedData,
      },
    };

    props.handleSubmit(userData);
  };

  const formik = useFormik({
    ...formikConfig,
    onSubmit,
  });

  return (
    <Card handleSubmit={formik.handleSubmit} isValid>
      <CardHeader {...props} />
      <SchemaFields
        formik={formik}
        schema={props.schema}
        sx={(theme) => ({
          display: "flex",
          flexDirection: "column",
          gap: theme.spacing(2),
        })}
      />
    </Card>
  );
}

export default PageComponent;
