openapi: 3.1.0
info:
  title: Plan✕ API
  version: 0.1.0
paths: {}
components:
  responses:
    SuccessMessage:
      description: Success message
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Success!"
    ErrorMessage:
      description: Error message
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Error!"
