name: Action failure notification

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  notifications:
    name: Failure notifications
    runs-on: ubuntu-22.04
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: planx-notifications-internal
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "#FF5733"
          SLACK_TITLE: ${{ inputs.environment }} deploy failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}
