name: Lint GHA workflows and actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.12
        with:
          args: >-
            .github/workflows/*.yml
            .github/actions/*/action.yml