name: Pizza Teardown (Manual)
on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        required: true
        type: number
        description: Pull Request number which should have its pizza destroyed

env:
  DOMAIN: planx.pizza

jobs:
  teardown_pizza:
    runs-on: ubuntu-22.04
    steps:
      - name: Remove vultr resources
        uses: theopensystemslab/vultr-action@v2.0
        with:
          action: destroy
          api_key: ${{ secrets.VULTR_API_KEY }}
          domain: ${{ env.DOMAIN }}
          os_type: alpine
          plan: vc2-1c-1gb
          pull_request_id: ${{  github.event.inputs.pull_request_id  }}
          region: lhr
          tag: manual-teardown
