name: Pizza Teardown (Manual)
on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        required: true
        type: integer
        description: Pull Request number which should have its pizza destroyed

env:
  DOMAIN: planx.pizza

jobs:
  teardown_pizza:
    runs-on: ubuntu-22.04
    steps:
      - name: Remove vultr resources
        uses: theopensystemslab/vultr-action@v1.15
        with:
          action: destroy
          api_key: ${{ secrets.VULTR_API_KEY }}
          domain: ${{ env.DOMAIN }}
          pullrequest_id: ${{  github.event.inputs.pull_request_id  }}
