name: Publish Packages
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - ben/document-viewer # TODO - remove after testing
    paths:
      - 'packages/**'

jobs:
  # All packages are assumed to have a `ci` script that runs any relevant CI tests
  test:
    name: Test Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # FIXME: this approch supports multiple packages but will run for every package when any change.
        project: 
          - "document-review"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        id: install-node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        working-directory: ./packages/${{ matrix.project }}

      - name: Setup pnpm cache
        id: setup-pnpm-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-${{ matrix.project }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.project }}-pnpm-store-

      - name: Install dependencies
        id: install-packages
        run: pnpm install
        working-directory: ./packages/${{ matrix.project }}

      - name: Run CI Script
        id: pnpm-ci
        run: pnpm ci
        working-directory: ./packages/${{ matrix.project }}

      # WIP
      #- name: Publish Package
      #  id: pnpm-publish
      #  run: pnpm publish
      #  working-directory: ./packages/${{ matrix.project }}
