name: Pulumi (Deploy Staging)

permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main

# When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress,
# the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled.
concurrency: staging_environment

env:
  DEPLOYMENT_ENVIRONMENT: staging
  LOCALPLANNING_SERVICES_DIRECTORY: apps/localplanning.services
  EDITOR_DIRECTORY: apps/editor.planx.uk

jobs:
  build_planx_frontend:
    name: Build PlanX frontend
    uses: ./.github/workflows/build-planx-frontend.yml
    secrets: inherit
    with:
      environment: staging
      vite-app-url: https://editor.planx.dev
      vite-api-url: https://api.editor.planx.dev
      vite-hasura-url: https://hasura.editor.planx.dev/v1/graphql
      vite-hasura-websocket: wss://hasura.editor.planx.dev/v1/graphql
      vite-sharedb-url: wss://sharedb.editor.planx.dev

  preview:
    name: Pulumi Up
    needs:
      - build_planx_frontend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-region: eu-west-2
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      - uses: ./.github/actions/setup-node-pnpm
      - run: pnpm install --frozen-lockfile
        working-directory: infrastructure/application
      - name: Download PlanX frontend build artifact
        uses: actions/download-artifact@v8
        with:
          name: planx_frontend_build
          path: ./${{ env.EDITOR_DIRECTORY }}/build
      - uses: pulumi/actions@v6
        with:
          command: up
          refresh: true
          stack-name: staging
          work-dir: infrastructure/application
          edit-pr-comment: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Invalidate CloudFront cache
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          DIST_ID=$(pulumi stack output cdnDistributionId --stack staging --cwd infrastructure/application)
          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"

  notifications:
    name: Notifications
    needs: preview
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      # Airbrake notification - https://airbrake.io/docs/features/deploy-tracking
      - name: Notify Airbrake of deploy
        id: airbrake-deploy
        uses: mtchavez/airbrake-deploy@v1
        with:
          project-id: ${{ secrets.AIRBRAKE_PROJECT_ID }}
          project-key: ${{ secrets.AIRBRAKE_PROJECT_KEY }}
          environment: ${{ env.DEPLOYMENT_ENVIRONMENT }}
          repository: https://github.com${{ github.repo }}
          revision: ${{ github.sha }}
          user: ${{ github.actor }}
      - name: Get Airbrake deploy response
        run: echo "The response was ${{ steps.airbrake-deploy.outputs.response }}"
      # Slack deployment notification
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: PlanX Deploy
          SLACK_COLOR: "#4F93E3"
          SLACK_TITLE: ${{ env.DEPLOYMENT_ENVIRONMENT }} deploy
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}

  failure_notification:
    name: Send failure notification
    needs: preview
    if: failure()
    uses: ./.github/workflows/action-failure.yml
    secrets: inherit
    with:
      environment: Staging
