name: Setup environment variables

on: 
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    secrets: 
      pizza_aws_access_key_id:
        required: true
      pizza_aws_secret_access_key:
        required: true

jobs:
  copy_secrets:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.pizza_aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.pizza_aws_secret_access_key }}
          aws-region: eu-west-2
      - name: Copy .env files from Staging S3 to the current working directory with AWS CLI
        run: | 
          aws s3 cp s3://pizza-secrets/root.env ./.env
          aws s3 cp s3://pizza-secrets/editor.env ./editor.planx.uk/.env
          aws s3 cp s3://pizza-secrets/api.env.test ./api.planx.uk/.env.test
      - name: Check if .env files exist
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".env, .env.staging, api.planx.uk/.env.test, editor.planx.uk/.env"
      - name: Files exist 
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All environment variable files successfully copied!
