name: Test

on: [push, pull_request]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: editor.planx.uk
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test
