name: Test and Build

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      FULL_DOMAIN:
        required: true
        type: string
      EDITOR_DIRECTORY:
        required: true
        type: string
      REACT_APP_GOOGLE_OAUTH_OVERRIDE:
        required: false
        type: string
      BUILD_STORYBOOK:
        required: false
        type: boolean
        default: false
    secrets:
      ORDNANCE_SURVEY_KEY:
        required: true
      AIRBRAKE_PROJECT_ID:
        required: true
      AIRBRAKE_PROJECT_KEY:
        required: true

jobs:
  test-and-build:
    name: Test and Build (Reusable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ inputs.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: ${{ inputs.EDITOR_DIRECTORY }}
      - run: pnpm test
        working-directory: ${{ inputs.EDITOR_DIRECTORY }}
      - run: pnpm build
        working-directory: ${{ inputs.EDITOR_DIRECTORY }}
        env:
          REACT_APP_AIRBRAKE_PROJECT_ID: ${{ secrets.AIRBRAKE_PROJECT_ID }}
          REACT_APP_AIRBRAKE_PROJECT_KEY: ${{ secrets.AIRBRAKE_PROJECT_KEY }}
          REACT_APP_API_URL: https://api.${{ inputs.FULL_DOMAIN }}
          REACT_APP_FEEDBACK_FISH_ID: 65f02de00b90d1
          REACT_APP_HASURA_URL: https://hasura.${{ inputs.FULL_DOMAIN }}/v1/graphql
          REACT_APP_ORDNANCE_SURVEY_KEY: ${{ secrets.ORDNANCE_SURVEY_KEY }}
          REACT_APP_SHAREDB_URL: wss://sharedb.${{ inputs.FULL_DOMAIN }}
          # needed because there's no API to change google's allowed OAuth URLs
          REACT_APP_GOOGLE_OAUTH_OVERRIDE: ${{ inputs.REACT_APP_GOOGLE_OAUTH_OVERRIDE }}
      - run: pnpm build-storybook
        if: ${{ inputs.BUILD_STORYBOOK }}
        # same env as above, if it's job.env it can't access existing env.[variable]
        env:
          REACT_APP_AIRBRAKE_PROJECT_ID: ${{ secrets.AIRBRAKE_PROJECT_ID }}
          REACT_APP_AIRBRAKE_PROJECT_KEY: ${{ secrets.AIRBRAKE_PROJECT_KEY }}
          REACT_APP_API_URL: https://api.${{ inputs.FULL_DOMAIN }}
          REACT_APP_FEEDBACK_FISH_ID: 65f02de00b90d1
          REACT_APP_HASURA_URL: https://hasura.${{ inpouts.FULL_DOMAIN }}/v1/graphql
          REACT_APP_ORDNANCE_SURVEY_KEY: ${{ secrets.ORDNANCE_SURVEY_KEY }}
          REACT_APP_SHAREDB_URL: wss://sharedb.${{ inputs.FULL_DOMAIN }}
          REACT_APP_GOOGLE_OAUTH_OVERRIDE: https://api.editor.planx.dev
        working-directory: ${{ inputs.EDITOR_DIRECTORY }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./${{ inputs.EDITOR_DIRECTORY }}/build
          if-no-files-found: error
