name: Vultr Update
on:
  pull_request:
    types: [synchronize]
    branches:
      - main

env:
  # DOMAIN: planx.club
  FULL_DOMAIN: ${{ github.event.number }}.planx.club
  VULTR_URL: https://${{ github.event.number }}.planx.club
  PULLREQUEST_ID: ${{ github.event.number }}

jobs:
  update_vultr_instance:
    runs-on: ubuntu-latest
    steps:
      - name: Create commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.FULL_DOMAIN }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 20m
          script: |
            git clone "${{ secrets.AUTHENTICATED_REPO_URL }}"
            cd planx-new
            git add . && git stash
            git fetch origin "pull/${{ env.PULLREQUEST_ID }}/head" && git checkout FETCH_HEAD
            sh scripts/pullrequest/update.sh

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vultr
          message: |
            Updated ${{ env.VULTR_URL }} to ${{ github.sha }}
