CREATE TABLE public.blpu_codes (
    description text NOT NULL,
    code text NOT NULL,
    value text NOT NULL
);
COMMENT ON TABLE public.blpu_codes IS 'Translates BLPU codes into PlanX data field values';
ALTER TABLE ONLY public.blpu_codes
    ADD CONSTRAINT blpu_codes_pkey PRIMARY KEY (code);

INSERT INTO blpu_codes (description, code, value) VALUES
  ('Commercial','C','commercial')
, ('Agricultural','CA','commercial.agriculture')
, ('Farm / Non-Residential Associated Building','CA01','commercial.agriculture.farm')
, ('Fishery','CA02','commercial.fish')
, ('Fish Farming','CA02FF','commercial.fish.farm')
, ('Fish Hatchery','CA02FH','commercial.fish.hatchery')
, ('Fish Processing','CA02FP','commercial.fish.processing')
, ('Oyster / Mussel Bed','CA02OY','commercial.fish.oysters')
, ('Horticulture','CA03','commercial.horticulture')
, ('Smallholding','CA03SH','commercial.horticulture.smallholding')
, ('Vineyard','CA03VY','commercial.horticulture.vineyard')
, ('Watercress Bed','CA03WB','commercial.horticulture.watercress')
, ('Slaughter House / Abattoir','CA04','commercial.abattoir')
, ('Ancillary Building','CB','commercial.ancilliary')
, ('Community Services','CC','commercial.community')
, ('Law Court','CC02','commercial.community.court')
, ('Prison','CC03','commercial.community.prison')
, ('HM Detention Centre','CC03HD','commercial.community.prison.detention')
, ('HM Prison Service','CC03PR','commercial.community.prison.service')
, ('Secure Residential Accommodation','CC03SC','commercial.community.prison.secureResidential')
, ('Public / Village Hall / Other Community Facility','CC04','commercial.community.hall')
, ('Youth Recreational / Social Club','CC04YR','commercial.community.hall.club')
, ('Public Convenience','CC05','commercial.community.wc')
, ('Cemetery / Crematorium / Graveyard. In Current Use.','CC06','commercial.community.cemetary')
, ('Columbarium','CC06CB','commercial.community.cemetary.columbarium')
, ('Crematorium','CC06CN','commercial.community.cemetary.crematorium')
, ('Chapel Of Rest','CC06CR','commercial.community.cemetary.chapelOfRest')
, ('Cemetery','CC06CY','commercial.community.cemetary.cemetary')
, ('Military Cemetery','CC06MC','commercial.community.cemetary.military')
, ('Mortuary','CC06MY','commercial.community.cemetary.mortuary')
, ('Church Hall / Religious Meeting Place / Hall','CC07','commercial.community.religious')
, ('Community Service Centre / Office','CC08','commercial.community.services')
, ('Public Household Waste Recycling Centre (HWRC)','CC09','commercial.community.HWRC')
, ('Recycling Site','CC10','commercial.community.recycling')
, ('CCTV','CC11','commercial.community.CCTV')
, ('Job Centre','CC12','commercial.community.employment')
, ('Education','CE','commercial.education')
, ('College','CE01','commercial.education.college')
, ('Further Education','CE01FE','commercial.education.college.further')
, ('Higher Education','CE01HE','commercial.education.college.higher')
, ('Children’s Nursery / Crèche','CE02','commercial.education.nursery')
, ('Preparatory / First / Primary / Infant / Junior / Middle School','CE03','commercial.education.school')
, ('First School','CE03FS','commercial.education.school.first')
, ('Infant School','CE03IS','commercial.education.school.infant')
, ('Junior School','CE03JS','commercial.education.school.junior')
, ('Middle School','CE03MS','commercial.education.school.middle')
, ('Non State Primary / Preparatory School','CE03NP','commercial.education.school.primary.private')
, ('Primary School','CE03PS','commercial.education.school.primary.state')
, ('Secondary / High School','CE04','commercial.education.secondarySchool')
, ('Non State Secondary School','CE04NS','commercial.education.secondarySchool.private')
, ('Secondary School','CE04SS','commercial.education.secondarySchool.state')
, ('University','CE05','commercial.education.university')
, ('Special Needs Establishment.','CE06','commercial.education.specialNeeds')
, ('Other Educational Establishment','CE07','commercial.education.other')
, ('Hotel / Motel / Boarding / Guest House','CH','commercial.guest')
, ('Boarding / Guest House / Bed And Breakfast / Youth Hostel','CH01','commercial.guest.hostel')
, ('Youth Hostel','CH01YH','commercial.guest.hostel.youth')
, ('Holiday Let/Accomodation/Short-Term Let Other Than CH01','CH02','commercial.guest.shortLet')
, ('Hotel/Motel','CH03','commercial.guest.hotel')
, ('Industrial Applicable to manufacturing, engineering, maintenance, storage / wholesale distribution and extraction sites','CI','commercial.industrial')
, ('Factory/Manufacturing','CI01','commercial.industrial.manufacturing')
, ('Aircraft Works','CI01AW','commercial.industrial.manufacturing.aircraft')
, ('Boat Building','CI01BB','commercial.industrial.manufacturing.boats')
, ('Brick Works','CI01BR','commercial.industrial.manufacturing.bricks')
, ('Brewery','CI01BW','commercial.industrial.manufacturing.beer')
, ('Cider Manufacture','CI01CD','commercial.industrial.manufacturing.cider')
, ('Chemical Works','CI01CM','commercial.industrial.manufacturing.chemicals')
, ('Cement Works','CI01CW','commercial.industrial.manufacturing.cement')
, ('Dairy Processing','CI01DA','commercial.industrial.manufacturing.dairy')
, ('Distillery','CI01DY','commercial.industrial.manufacturing.distillery')
, ('Flour Mill','CI01FL','commercial.industrial.manufacturing.flour')
, ('Food Processing','CI01FO','commercial.industrial.manufacturing.food')
, ('Glassworks','CI01GW','commercial.industrial.manufacturing.glass')
, ('Manufacturing','CI01MG','commercial.industrial.manufacturing.other')
, ('Oast House','CI01OH','commercial.industrial.manufacturing.hops')
, ('Oil Refining','CI01OR','commercial.industrial.manufacturing.oil')
, ('Pottery Manufacturing','CI01PG','commercial.industrial.manufacturing.pottery')
, ('Paper Mill','CI01PM','commercial.industrial.manufacturing.paper')
, ('Printing Works','CI01PW','commercial.industrial.manufacturing.printing')
, ('Sugar Refinery','CI01SR','commercial.industrial.manufacturing.sugar')
, ('Steel Works','CI01SW','commercial.industrial.manufacturing.steel')
, ('Timber Mill','CI01TL','commercial.industrial.manufacturing.timber')
, ('Winery','CI01WN','commercial.industrial.manufacturing.wine')
, ('Shipyard','CI01YD','commercial.industrial.manufacturing.ships')
, ('Mineral / Ore Working / Quarry / Mine','CI02','commercial.industrial.extraction')
, ('Mineral Mining / Active','CI02MA','commercial.industrial.extraction.mining')
, ('Mineral Distribution / Storage','CI02MD','commercial.industrial.extraction.distribution')
, ('Mineral Processing','CI02MP','commercial.industrial.extraction.processing')
, ('Oil / Gas Extraction / Active','CI02OA','commercial.industrial.extraction.oilGas')
, ('Mineral Quarrying / Open Extraction / Active','CI02QA','commercial.industrial.extraction.quarrying')
, ('Workshop / Light Industrial','CI03','commercial.industrial.light')
, ('Servicing Garage','CI03GA','commercial.industrial.light.garage')
, ('Warehouse / Store / Storage Depot','CI04','commercial.industrial.light.storage')
, ('Crop Handling / Storage','CI04CS','commercial.industrial.light.storage.crops')
, ('Postal Sorting / Distribution','CI04PL','commercial.industrial.light.storage.post')
, ('Solid Fuel Storage','CI04SO','commercial.industrial.light.storage.solidFuel')
, ('Timber Storage','CI04TS','commercial.industrial.light.storage.timber')
, ('Wholesale Distribution','CI05','commercial.industrial.distribution')
, ('Solid Fuel Distribution','CI05SF','commercial.industrial.distribution.solidFueld')
, ('Timber Distribution','CI05TD','commercial.industrial.distribution.timber')
, ('Recycling Plant','CI06','commercial.industrial.recycling')
, ('Incinerator / Waste Transfer Station','CI07','commercial.industrial.incineration')
, ('Maintenance Depot','CI08','commercial.industrial.maintenanceDepot')
, ('Leisure - Applicable to recreational sites and enterprises','CL','commercial.leisure')
, ('Amusements','CL01','commercial.leisure.amusements')
, ('Leisure Pier','CL01LP','commercial.leisure.amusements.pier')
, ('Holiday / Campsite','CL02','commercial.leisure.holiday')
, ('Camping','CL02CG','commercial.leisure.holiday.camping')
, ('Caravanning','CL02CV','commercial.leisure.holiday.caravanning')
, ('Holiday Accommodation','CL02HA','commercial.leisure.holiday.accommodation')
, ('Holiday Centre','CL02HO','commercial.leisure.holiday.centre')
, ('Youth Organisation Camp','CL02YC','commercial.leisure.holiday.youth')
, ('Library','CL03','commercial.leisure.library')
, ('Reading Room','CL03RR','commercial.leisure.library.readingRoom')
, ('Museum / Gallery','CL04','commercial.leisure.museum')
, ('Art Centre / Gallery','CL04AC','commercial.leisure.museum.art')
, ('Aviation Museum','CL04AM','commercial.leisure.museum.aviation')
, ('Heritage Centre','CL04HG','commercial.leisure.museum.heritage')
, ('Industrial Museum','CL04IM','commercial.leisure.museum.industrial')
, ('Military Museum','CL04MM','commercial.leisure.museum.military')
, ('Maritime Museum','CL04NM','commercial.leisure.museum.maritime')
, ('Science Museum','CL04SM','commercial.leisure.museum.science')
, ('Transport Museum','CL04TM','commercial.leisure.museum.transport')
, ('Indoor / Outdoor Leisure / Sporting Activity / Centre','CL06','commercial.leisure.sport')
, ('Athletics Facility','CL06AH','commercial.leisure.sport.athletics')
, ('Bowls Facility','CL06BF','commercial.leisure.sport.bowls')
, ('Cricket Facility','CL06CK','commercial.leisure.sport.cricket')
, ('Curling Facility','CL06CU','commercial.leisure.sport.curling')
, ('Diving / Swimming Facility','CL06DS','commercial.leisure.sport.swimming')
, ('Equestrian Sports Facility','CL06EQ','commercial.leisure.sport.equestrian')
, ('Football Facility','CL06FB','commercial.leisure.sport.football')
, ('Fishing / Angling Facility','CL06FI','commercial.leisure.sport.fishing')
, ('Golf Facility','CL06GF','commercial.leisure.sport.golf')
, ('Gliding Facility','CL06GL','commercial.leisure.sport.gliding')
, ('Greyhound Racing Facility','CL06GR','commercial.leisure.sport.dogracing')
, ('Hockey Facility','CL06HF','commercial.leisure.sport.hockey')
, ('Horse Racing Facility','CL06HR','commercial.leisure.sport.horseracing')
, ('Historic Vessel / Aircraft / Vehicle','CL06HV','commercial.leisure.sport.historicVehicles')
, ('Activity / Leisure / Sports Centre','CL06LS','commercial.leisure.sport.centre')
, ('Model Sports Facility','CL06ME','commercial.leisure.sport.model')
, ('Motor Sports Facility','CL06MF','commercial.leisure.sport.motor')
, ('Playing Field','CL06PF','commercial.leisure.sport.playingField')
, ('Racquet Sports Facility','CL06QS','commercial.leisure.sport.racquet')
, ('Rugby Facility','CL06RF','commercial.leisure.sport.rugby')
, ('Recreation Ground','CL06RG','commercial.leisure.sport.recreationGround')
, ('Shinty Facility','CL06SI','commercial.leisure.sport.shinty')
, ('Skateboarding Facility','CL06SK','commercial.leisure.sport.skateboarding')
, ('Civilian Firing Facility','CL06SX','commercial.leisure.sport.firing')
, ('Tenpin Bowling Facility','CL06TB','commercial.leisure.sport.tenpin')
, ('Public Tennis Court','CL06TN','commercial.leisure.sport.tennis')
, ('Water Sports Facility','CL06WA','commercial.leisure.sport.water')
, ('Winter Sports Facility','CL06WP','commercial.leisure.sport.winter')
, ('Wildlife Sports Facility','CL06WY','commercial.leisure.sport.wildlife')
, ('Cycling Sports Facility','CL06YF','commercial.leisure.sport.cycling')
, ('Bingo Hall / Cinema / Conference / Exhibition Centre / Theatre / Concert Hall','CL07','commercial.leisure.entertainment')
, ('Cinema','CL07CI','commercial.leisure.entertainment.cinema')
, ('Entertainment Complex','CL07EN','commercial.leisure.entertainment.mixed')
, ('Conference / Exhibition Centre','CL07EX','commercial.leisure.entertainment.exhibition')
, ('Theatre','CL07TH','commercial.leisure.entertainment.theatre')
, ('Zoo / Theme Park','CL08','commercial.leisure.park.zoo')
, ('Amusement Park','CL08AK','commercial.leisure.park.amusement')
, ('Aquatic Attraction','CL08AQ','commercial.leisure.park.aquatic')
, ('Model Village Site','CL08MX','commercial.leisure.park.model')
, ('Wildlife / Zoological Park','CL08WZ','commercial.leisure.park.wildlife')
, ('Beach Hut (Recreational, Non-Residential Use Only)','CL09','commercial.leisure.beachHut')
, ('Licensed Private Members’ Club','CL10','commercial.leisure.club.private')
, ('Recreational / Social Club','CL10RE','commercial.leisure.club.social')
, ('Arena / Stadium','CL11','commercial.leisure.arena')
, ('Stadium','CL11SD','commercial.leisure.arena.stadium')
, ('Showground','CL11SJ','commercial.leisure.arena.showground')
, ('Medical','CM','commercial.medical')
, ('Dentist','CM01','commercial.medical.dentist')
, ('General Practice Surgery / Clinic','CM02','commercial.medical.GP')
, ('Health Centre','CM02HC','commercial.medical.healthCentre')
, ('Health Care Services','CM02HL','commercial.medical.healthServices')
, ('Hospital / Hospice','CM03','commercial.medical.care')
, ('Care home/Hospice','CM03HI','commercial.medical.care.home')
, ('Hospital','CM03HP','commercial.medical.care.hospital')
, ('Medical / Testing / Research Laboratory','CM04','commercial.medical.lab')
, ('Professional Medical Service','CM05','commercial.medical.professional')
, ('Assessment / Development Services','CM05ZS','commercial.medical.assessment')
, ('Animal Centre','CN','commercial.animals')
, ('Cattery / Kennel','CN01','commercial.animals.kennelsCattery')
, ('Animal Services','CN02','commercial.animals.services')
, ('Animal Quarantining','CN02AX','commercial.animals.services.quarantine')
, ('Equestrian','CN03','commercial.animals.equestrian')
, ('Horse Racing / Breeding Stable','CN03HB','commercial.animals.equestrian.racing')
, ('Commercial Stabling / Riding','CN03SB','commercial.animals.equestrian.riding')
, ('Vet / Animal Medical Treatment','CN04','commercial.animals.vet')
, ('Animal / Bird / Marine Sanctuary','CN05','commercial.animals.sanctuary')
, ('Animal Sanctuary','CN05AN','commercial.animals.sanctuary.animals')
, ('Marine Sanctuary','CN05MR','commercial.animals.sanctuary.marine')
, ('Office','CO','commercial.office')
, ('Office / Work Studio','CO01','commercial.office.workspace')
, ('Embassy /, High Commission / Consulate','CO01EM','commercial.office.workspace.embassy')
, ('Film Studio','CO01FM','commercial.office.workspace.film')
, ('Central Government Service','CO01GV','commercial.office.workspace.gov.national')
, ('Local Government Service','CO01LG','commercial.office.workspace.gov.local')
, ('Broadcasting (TV / Radio)','CO02','commercial.office.broadcasting')
, ('Retail','CR','commercial.retail')
, ('Bank / Financial Service','CR01','commercial.retail.financial')
, ('Retail Service Agent','CR02','commercial.retail.services')
, ('Post Office','CR02PO','commercial.retail.post')
, ('Market (Indoor / Outdoor)','CR04','commercial.retail.market')
, ('Fish Market','CR04FK','commercial.retail.market.fish')
, ('Fruit / Vegetable Market','CR04FV','commercial.retail.market.fruit')
, ('Livestock Market','CR04LV','commercial.retail.market.livestock')
, ('Petrol Filling Station','CR05','commercial.retail.fuel')
, ('Public House / Bar / Nightclub','CR06','commercial.retail.drinking')
, ('Restaurant / Cafeteria','CR07','commercial.retail.restaurant')
, ('Shop / Showroom','CR08','commercial.retail.showroom')
, ('Shop','CR08 ','commercial.retail.shop')
, ('Garden Centre','CR08GC','commercial.retail.shop.gardenCentre')
, ('Other Licensed Premise / Vendor','CR09','commercial.retail.licensedPremises')
, ('Fast Food Outlet / Takeaway (Hot / Cold)','CR10','commercial.retail.takeaway')
, ('Automated Teller Machine (ATM)','CR11','commercial.retail.atm')
, ('Storage Land','CS','commercial.storageLand')
, ('General Storage Land','CS01','commercial.storageLand.general')
, ('Builders’ Yard','CS02','commercial.storageLand.building')
, ('Transport','CT','commercial.transport')
, ('Airfield / Airstrip / Airport / Air Transport Infrastructure Facility','CT01','commercial.transport.air')
, ('Airfield','CT01AF','commercial.transport.air.airfield')
, ('Air Transport Infrastructure Services','CT01AI','commercial.transport.air.infrastructure')
, ('Airport','CT01AP','commercial.transport.air.airport')
, ('Air Passenger Terminal','CT01AY','commercial.transport.air.passengerTerminal')
, ('Helicopter Station','CT01HS','commercial.transport.air.helicopterStation')
, ('Heliport / Helipad','CT01HT','commercial.transport.air.heliport')
, ('Bus Shelter','CT02','commercial.transport.bus')
, ('Car / Coach / Commercial Vehicle / Taxi Parking / Park And Ride Site','CT03','commercial.transport.parking')
, ('Public Park And Ride','CT03PK','commercial.transport.parking.parkAndRide')
, ('Public Car Parking','CT03PP','commercial.transport.parking.car')
, ('Public Coach Parking','CT03PU','commercial.transport.parking.coach')
, ('Public Commercial Vehicle Parking','CT03VP','commercial.transport.parking.commercialVehicle')
, ('Goods Freight Handling / Terminal','CT04','commercial.transport.freight')
, ('Air Freight Terminal','CT04AE','commercial.transport.freight.air')
, ('Container Freight','CT04CF','commercial.transport.freight.container')
, ('Road Freight Transport','CT04RH','commercial.transport.freight.road')
, ('Rail Freight Transport','CT04RT','commercial.transport.freight.rail')
, ('Marina','CT05','commercial.transport.marina')
, ('Mooring','CT06','commercial.transport.mooring')
, ('Railway Asset','CT07','commercial.transport.railAsset')
, ('Station / Interchange / Terminal / Halt','CT08','commercial.transport.terminal')
, ('Bus station','CT08BC','commercial.transport.terminal.bus')
, ('Train station','CT08RS','commercial.transport.terminal.train')
, ('Vehicular Rail Terminal','CT08VH','commercial.transport.terminal.vehicularRail')
, ('Transport Track / Way','CT09','commercial.transport.track')
, ('Cliff Railway','CT09CL','commercial.transport.track.cliff')
, ('Chair Lift / Cable Car / Ski Tow','CT09CX','commercial.transport.track.cable')
, ('Monorail','CT09MO','commercial.transport.track.monorail')
, ('Vehicle Storage','CT10','commercial.transport.storage')
, ('Boat Storage','CT10BG','commercial.transport.storage.boat')
, ('Bus / Coach Depot','CT10BU','commercial.transport.storage.bus')
, ('Transport Related Infrastructure','CT11','commercial.transport.infrastructure')
, ('Aqueduct','CT11AD','commercial.transport.infrastructure.aqueduct')
, ('Lock','CT11LK','commercial.transport.infrastructure.lock')
, ('Weir','CT11WE','commercial.transport.infrastructure.weir')
, ('Weighbridge / Load Gauge','CT11WG','commercial.transport.infrastructure.weighing')
, ('Overnight Lorry Park','CT12','commercial.transport.overnightLorryPark')
, ('Harbour / Port / Dock / Dockyard / Slipway / Landing Stage / Pier / Jetty / Pontoon / Terminal / Berthing / Quay','CT13','commercial.transport.dock')
, ('Passenger Ferry Terminal','CT13FR','commercial.transport.dock.ferry.passengers')
, ('Non-Tanker Nautical Berthing','CT13NB','commercial.transport.dock.generalBerth')
, ('Nautical Refuelling Facility','CT13NF','commercial.transport.dock.refuelling')
, ('Slipway','CT13SA','commercial.transport.dock.slipway')
, ('Ship Passenger Terminal','CT13SP','commercial.transport.dock.passenger')
, ('Tanker Berthing','CT13TK','commercial.transport.dock.tankerBerth')
, ('Vehicular Ferry Terminal','CT13VF','commercial.transport.dock.ferry.vehicles')
, ('Utility','CU','commercial.utility')
, ('Electricity Sub-Station','CU01','commercial.utility.SubStation')
, ('Landfill','CU02','commercial.utility.landfill')
, ('Power Station / Energy Production','CU03','commercial.utility.electricity')
, ('Electricity Distribution Facility','CU03ED','commercial.utility.electricity.distribution')
, ('Electricity Production Facility','CU03EP','commercial.utility.electricity.production')
, ('Wind Farm','CU03WF','commercial.utility.electricity.windFarm')
, ('Wind Turbine','CU03WU','commercial.utility.electricity.windTurbine')
, ('Pump House / Pumping Station / Water Tower','CU04','commercial.utility.water')
, ('Water Controlling / Pumping','CU04WC','commercial.utility.water.pump.control')
, ('Water Distribution / Pumping','CU04WD','commercial.utility.water.pump.distribution')
, ('Water Quality Monitoring','CU04WM','commercial.utility.water.qualityMonitoring')
, ('Water Storage','CU04WS','commercial.utility.water.storage')
, ('Waste Water Distribution / Pumping','CU04WW','commercial.utility.water.waste')
, ('Telecommunication','CU06','commercial.utility.telecoms')
, ('Telecommunications Mast','CU06TE','commercial.utility.telecoms.mast')
, ('Telephone Exchange','CU06TX','commercial.utility.telecoms.exhange')
, ('Water / Waste Water / Sewage Treatment Works','CU07','commercial.utility.waterTreatment')
, ('Waste Water Treatment','CU07WR','commercial.utility.waterTreatment.waste')
, ('Water Treatment','CU07WT','commercial.utility.waterTreatment.water')
, ('Gas / Oil Storage / Distribution','CU08','commercial.utility.oilGas')
, ('Gas Governor','CU08GG','commercial.utility.oilGas.gasGovernor')
, ('Gas Holder','CU08GH','commercial.utility.oilGas.gasHolder')
, ('Oil Terminal','CU08OT','commercial.utility.oilGas.oilTerminal')
, ('Other Utility Use','CU09','commercial.utility.other')
, ('Cable Terminal Station','CU09CQ','commercial.utility.other.cableTerminal')
, ('Observatory','CU09OV','commercial.utility.other.observatory')
, ('Radar Station','CU09RA','commercial.utility.other.radar')
, ('Satellite Earth Station','CU09SE','commercial.utility.other.satelliteEarth')
, ('Waste Management','CU10','commercial.utility.wasteManagement')
, ('Telephone Box','CU11','commercial.utility.publicPhone.box')
, ('Other Public Telephones','CU11OP','commercial.utility.publicPhone.other')
, ('Dam','CU12','commercial.utility.dam')
, ('Emergency / Rescue Service','CX','commercial.emergency')
, ('Nautical Navigation Beacon / Light','OA02NL','other.navigation.nautical.beacon')
, ('Aid To Road Navigation','OA03','other.navigation.road')
, ('Guide Post','OA03GP','other.navigation.guidePost')
, ('Coastal Protection / Flood Prevention','OC','other.coastal')
, ('Boulder Wall / Sea Wall','OC01','other.coastal.wall')
, ('Flood Gate / Flood Sluice Gate / Flood Valve','OC02','other.coastal.floodGate')
, ('Groyne','OC03','other.coastal.groyne')
, ('Rip-Rap','OC04','other.coastal.ripRap')
, ('Emergency Support','OE','other.emergency')
, ('Beach Office / First Aid Facility','OE01','other.emergency.firstAid')
, ('Emergency Telephone (Non Motorway)','OE02','other.emergency.telephone')
, ('Fire Alarm Structure / Fire Observation Tower / Fire Beater Facility','OE03','other.emergency.fire')
, ('Emergency Equipment Point / Emergency Siren / Warning Flag','OE04','other.emergency.warning')
, ('Lifeguard Facility','OE05','other.emergency.lifeguard')
, ('LIfe / Belt / Buoy / Float / Jacket / Safety Rope','OE06','other.emergency.floatAids')
, ('Street Furniture','OF','other.streetFurniture')
, ('Agricultural Support Objects','OG','other.agriculture')
, ('Fish Ladder / Lock / Pen / Trap','OG01','other.agriculture.fishPen')
, ('Livestock Pen / Dip','OG02','other.agriculture.livestockPen')
, ('Currick','OG03','other.agriculture.currick')
, ('Slurry Bed / Pit','OG04','other.agriculture.slurry')
, ('Historical Site / Object','OH','other.historic')
, ('Historic Structure / Object','OH01','other.historic.structure')
, ('Industrial Support','OI','other.industrial')
, ('Adit / Incline / Level','OI01','other.industrial.aditIncline')
, ('Caisson / Dry Dock / Grid','OI02','other.industrial.caissonDock')
, ('Channel / Conveyor / Conduit / Pipe','OI03','other.industrial.channel')
, ('Chimney / Flue','OI04','other.industrial.chimney')
, ('Crane / Hoist / Winch / Material Elevator','OI05','other.industrial.crane')
, ('Flare Stack','OI06','other.industrial.flareStack')
, ('Hopper / Silo / Cistern / Tank','OI07','other.industrial.siloTank')
, ('Grab / Skip / Other Industrial Waste Machinery / Discharging','OI08','other.industrial.discharge')
, ('Kiln / Oven / Smelter','OI09','other.industrial.kiln')
, ('Manhole / Shaft','OI10','other.industrial.manholeShaft')
, ('Industrial Overflow / Sluice / Valve / Valve Housing','OI11','other.industrial.overflowSluiceValve')
, ('Cooling Tower','OI12','other.industrial.coolingTower')
, ('Solar Panel / Waterwheel','OI13','other.industrial.solarPanel')
, ('Telephone Pole / Post','OI14','other.industrial.pylon.telecom')
, ('Electricity Distribution Pole / Pylon','OI15','other.industrial.pylon.electricity')
, ('Significant Natural Object','ON','other.natural')
, ('Boundary / Significant / Historic Tree / Pollard','ON01','other.natural.tree')
, ('Boundary / Significant Rock / Boulder','ON02','other.natural.rock')
, ('Natural Hole (Blow / Shake / Swallow)','ON03','other.natural.hole')
, ('Ornamental / Cultural Object','OO','other.ornamental')
, ('Mausoleum / Tomb / Grave','OO02','other.ornamental.tomb')
, ('Simple Ornamental Object','OO03','other.ornamental.object')
, ('Maze','OO04','other.ornamental.maze')
, ('Sport / Leisure Support','OP','other.leisure')
, ('Butt / Hide','OP01','other.leisure.hide')
, ('Gallop / Ride','OP02','other.leisure.gallop')
, ('Miniature Railway','OP03','other.leisure.modelRailway')
, ('Royal Mail Infrastructure','OR','other.mail')
, ('Postal Box','OR01','other.mail.postBox')
, ('Postal Delivery Box / Pouch','OR02','other.mail.deliveryBox')
, ('PO Box','OR03','other.mail.POBox')
, ('Additional Mail / Packet Addressee','OR04','other.mail.additionalAddressee')
, ('Scientific / Observation Support','OS','other.scientific')
, ('Meteorological Station / Equipment','OS01','other.scientific.meteo')
, ('Radar / Satellite Infrastructure','OS02','other.scientific.radarSatellite')
, ('Telescope / Observation Infrastructure / Astronomy','OS03','other.scientific.astronomy')
, ('Transport Support','OT','other.transport')
, ('Cattle Grid / Ford','OT01','other.transport.cattleGridFord')
, ('Elevator / Escalator / Steps','OT02','other.transport.stepsLiftEscalator')
, ('Footbridge / Walkway','OT03','other.transport.bridge')
, ('Pole / Post / Bollard (Restricting Vehicular Access)','OT04','other.transport.post')
, ('Subway / Underpass','OT05','other.transport.subway')
, ('Customs Inspection Facility','OT06','other.transport.customs')
, ('Lay-By','OT07','other.transport.layby')
, ('Level Crossing','OT08','other.transport.rail.crossing.vehicles')
, ('Mail Pick Up','OT09','other.transport.mailPickUp')
, ('Railway Pedestrian Crossing','OT10','other.transport.rail.crossing.pedestrian')
, ('Railway Buffer','OT11','other.transport.rail.buffer')
, ('Rail Drag','OT12','other.transport.rail.drag')
, ('Rail Infrastructure Services','OT13','other.transport.rail.infrastructure')
, ('Rail Kilometre Distance Marker','OT14','other.transport.rail.marker.km')
, ('Railway Lighting','OT15','other.transport.rail.lighting')
, ('Rail Mile Distance Marker','OT16','other.transport.rail.market.mile')
, ('Railway Turntable','OT17','other.transport.rail.turntable')
, ('Rail Weighbridge','OT18','other.transport.rail.weighbridge')
, ('Rail Signalling','OT19','other.transport.rail.signals')
, ('Railway Traverse','OT20','other.transport.rail.traverse')
, ('Goods Tramway','OT21','other.transport.goodsTramway')
, ('Road Drag','OT22','other.transport.road.drag')
, ('Vehicle Dip','OT23','other.transport.road.vehicleDip')
, ('Road Turntable','OT24','other.transport.road.turntable')
, ('Road Mile Distance Marker','OT25','other.transport.road.marker.mile')
, ('Road Kilometre Distance Marker','OT26','other.transport.road.market.km')
, ('Road Infrastructure Services','OT27','other.transport.road.infrastructure')
, ('Unsupported Site','OU','other.unsupported')
, ('Cycle Parking Facility','OU01','other.unsupported.cycleParking')
, ('Picnic / Barbeque Site','OU04','other.unsupported.picnic')
, ('Travelling Persons Site','OU05','other.unsupported.travellingPersons')
, ('Shelter (Not Including Bus Shelter)','OU08','other.unsupported.shelter')
, ('Parent Shell','P','parent')
, ('Property Shell','PP','parent.property')
, ('Street Record','PS','parent.street')
, ('Residential','R','residential')
, ('Ancillary Building','RB','residential.building')
, ('Car Park Space','RC','residential.carParkingSpace')
, ('Allocated Parking','RC01','residential.carParkingSpace.allocated')
, ('Residential dwelling','RD','residential.dwelling')
, ('Caravan','RD01','residential.dwelling.caravan')
, ('Detached','RD02','residential.dwelling.house.detached')
, ('Semi-detached','RD03','residential.dwelling.house.semiDetached')
, ('Terrace','RD04','residential.dwelling.house.terrace')
, ('Flat','RD06','residential.dwelling.flat')
, ('House Boat','RD07','residential.dwelling.boat')
, ('Sheltered Accommodation','RD08','residential.dwelling.shelteredAccommodation')
, ('Privately Owned Holiday Caravan / Chalet','RD10','residential.dwelling.holiday')
, ('Garage','RG','residential.garage')
, ('Lock-Up Garage / Garage Court','RG02','residential.garage')
, ('House In Multiple Occupation','RH','residential.HMO')
, ('HMO Parent','RH01','residential.HMO.parent')
, ('HMO Bedsit / Other Non Self Contained Accommodation','RH02','residential.HMO.bedsit')
, ('HMO Not Further Divided','RH03','residential.HMO.undivided')
, ('Residential Institution','RI','residential.institution')
, ('Care / Nursing Home','RI01','residential.institution.care')
, ('Communal Residence','RI02','residential.institution.communal')
, ('Non-Commercial Lodgings','RI02NC','residential.institution.noncommercial')
, ('Religious Community','RI02RC','residential.institution.religious')
, ('Residential Education','RI03','residential.institution.education')
, ('Unclassified','U','unclassified')
, ('Awaiting Classification','UC','unclassified.awaitingclassification')
, ('Pending Internal Investigation','UP','unclassified.pendingInvestigation')
, ('Dual Use','X','dualUse')
, ('Object of Interest','Z','object')
, ('Archaeological Dig Site','ZA','object.archaeological')
, ('Monument','ZM','object.monument')
, ('Obelisk / Milestone / Standing Stone','ZM01','object.monument.vertical')
, ('Obelisk','ZM01OB','object.monument.vertical.obelisk')
, ('Standing Stone','ZM01ST','object.monument.vertical.standingStone')
, ('Memorial / Market Cross','ZM02','object.monument.memorial')
, ('Statue','ZM03','object.monument.statue')
, ('Castle / Historic Ruin','ZM04','object.monument.ruin')
, ('Other Structure','ZM05','object.monument.other')
, ('Boundary Stone','ZM05BS','object.monument.other.boundaryStone')
, ('Cascade / Fountain','ZM05CE','object.monument.other.waterFeature')
, ('Permanent Art Display / Sculpture','ZM05PN','object.monument.other.art')
, ('Windmill (Inactive)','ZM05WI','object.monument.other.windmill')
, ('Stately Home','ZS','object.statelyHome')
, ('Underground Feature','ZU','object.underground')
, ('Cave','ZU01','object.underground.cave')
, ('Pothole / Natural Hole','ZU04','object.underground.hole')
, ('Other Underground Feature','ZV','object.underground.other')
, ('Cellar','ZV01','object.underground.other.cellar')
, ('Disused Mine','ZV02','object.underground.other.extraction')
, ('Mineral Mining / Inactive','ZV02MI','object.underground.other.extraction.mine')
, ('Oil And / Gas Extraction/ Inactive','ZV02OI','object.underground.other.extraction.oilGas')
, ('Mineral Quarrying And / Open Extraction / Inactive','ZV02QI','object.underground.other.extraction.quarry')
, ('Well / Spring','ZV03','object.underground.other.water')
, ('Spring','ZV03SG','object.underground.other.water.spring')
, ('Well','ZV03WL','object.underground.other.water.well')
, ('Place Of Worship','ZW','object.religious')
, ('Religious building','ZW99','object.religious.building')
, ('Abbey','ZW99AB','object.religious.building.abbey')
, ('Cathedral','ZW99CA','object.religious.building.cathedral')
, ('Church','ZW99CH','object.religious.building.church')
, ('Chapel','ZW99CP','object.religious.building.chapel')
, ('Gurdwara','ZW99GU','object.religious.building.gurdwara')
, ('Kingdom Hall','ZW99KH','object.religious.building.kingdomHall')
, ('Lych Gate','ZW99LG','object.religious.building.lychGate')
, ('Mosque','ZW99MQ','object.religious.building.mosque')
, ('Minster','ZW99MT','object.religious.building.minster')
, ('Stupa','ZW99SU','object.religious.building.stupa')
, ('Synagogue','ZW99SY','object.religious.building.synagogue')
, ('Temple','ZW99TP','object.religious.building.temple')
;
